// Abende (M5): Liste, Vorschlag, Terminabstimmung, Absage, Finde-Fenster, Rückmeldung, Kontakt, Nachbesprechung.
import { af, type AddressForm } from "./form";

export const abende = (f: AddressForm) => ({
  title: "Abende",
  lead: af(
    f,
    "Ihre Vorschläge und Abende in Partner-Lokalen. Jeder Vorschlag ist von einem Menschen geprüft.",
    "Deine Vorschläge und Abende in Partner-Lokalen. Jeder Vorschlag ist von einem Menschen geprüft.",
  ),
  upcomingTitle: "Kommende",
  pastTitle: "Vergangene",
  emptyTitle: "Noch keine Abende",
  emptyText: af(
    f,
    "Nach dem Gespräch mit Viola schlagen wir Ihnen alle 14 Tage ein Gegenüber vor. Damit es passt, tragen Sie Ihre freien Abende ein.",
    "Nach dem Gespräch mit Viola schlagen wir dir alle 14 Tage ein Gegenüber vor. Damit es passt, trägst du deine freien Abende ein.",
  ),
  pastEmpty: "Noch keine vergangenen Abende.",
  toAvailability: "Freie Abende eintragen",
  toConversation: "Zum Gespräch mit Viola",
  open: "Öffnen",
  withName: (name: string | null) => (name ? `Abend mit ${name}` : "Abend"),
  proposalWith: (name: string | null) => (name ? `Vorschlag: ein Abend mit ${name}` : "Vorschlag für einen Abend"),
  at: (venue: string, city?: string | null) => (city ? `${venue}, ${city}` : venue),
  states: {
    proposed: "Vorschlag",
    time_requested: "Uhrzeit wird abgestimmt",
    time_countered: "Uhrzeit wird abgestimmt",
    confirmed: "bestätigt",
    declined: "abgelehnt",
    lapsed: "Frist abgelaufen",
    cancelled_early: "abgesagt",
    cancelled_late: "kurzfristig abgesagt",
    happened: "stattgefunden",
    no_show: "nicht stattgefunden",
  } as Record<string, string>,
  actions: {
    choose_time: af(f, "Sie sind dran: Uhrzeit wählen", "Du bist dran: Uhrzeit wählen"),
    answer_time: af(f, "Sie sind dran: Uhrzeit bestätigen", "Du bist dran: Uhrzeit bestätigen"),
    wait: (name: string | null) => (name ? `${name} ist dran` : "Das Gegenüber ist dran"),
    prepare: "Der Abend steht",
    find: "Jetzt: Gegenüber finden",
    feedback: af(f, "Wie war Ihr Abend?", "Wie war dein Abend?"),
    contact: "Kontaktdaten freigegeben",
    debrief: "Nachbesprechung möglich",
    none: "",
  } as Record<string, string | ((name: string | null) => string)>,
  deadline: (when: string) => `Antwort ${when}`,
  noDeadline: "",
  timesLabel: "Uhrzeiten",

  // Detail
  back: "Alle Abende",
  whyTitle: af(f, "Warum Sie beide", "Warum ihr beide"),
  venueTitle: "Das Lokal",
  address: "Adresse",
  transport: "Mit Bus und Bahn",
  accessibility: "Barrierefreiheit",
  noInfo: "keine Angabe",
  mapHint: "Die Adresse lässt sich in jeder Karten-App suchen.",
  reservationLabel: "Reserviert unter",
  reservationValue: (name: string, persons: number) => `„${name}“, ${persons} Personen`,
  tableCode: "Tisch-Code",
  tableCodeHint: af(f, "Nennen Sie den Code im Lokal, falls gefragt.", "Nenn den Code im Lokal, falls gefragt."),
  stepTitle: "Nächster Schritt",
  deadlineNote: (when: string) =>
    af(f, `Bitte antworten Sie ${when}. Ohne Antwort endet der Vorschlag.`, `Bitte antworte ${when}. Ohne Antwort endet der Vorschlag.`),
  deadlineNoteShort: (when: string) => `Frist: ${when}`,

  chooseTitle: "Wann passt es?",
  chooseLead: (max: number) =>
    af(
      f,
      `Wählen Sie 1 bis ${max} Uhrzeiten. Ihr Gegenüber bestätigt dann eine davon oder schlägt eine andere vor.`,
      `Wähle 1 bis ${max} Uhrzeiten. Dein Gegenüber bestätigt dann eine davon oder schlägt eine andere vor.`,
    ),
  proposedBadge: "vorgeschlagen",
  sharedBadge: af(f, "passt in Ihre freien Zeiten", "passt in eure freien Zeiten"),
  noOptions: af(
    f,
    "Gerade ist keine Uhrzeit mit freiem Tisch übrig. Sie können den Vorschlag ablehnen; wir suchen beim nächsten Mal neu.",
    "Gerade ist keine Uhrzeit mit freiem Tisch übrig. Du kannst den Vorschlag ablehnen; wir suchen beim nächsten Mal neu.",
  ),
  chosen: (n: number, max: number) => `${n} von höchstens ${max} gewählt`,
  sendTimes: "Uhrzeiten senden",
  sending: "Wird gesendet …",
  answerTitle: (name: string | null) => (name ? `${name} schlägt vor` : af(f, "Ihr Gegenüber schlägt vor", "Dein Gegenüber schlägt vor")),
  answerLead: af(f, "Bestätigen Sie eine Uhrzeit. Dann reservieren wir den Tisch.", "Bestätige eine Uhrzeit. Dann reservieren wir den Tisch."),
  confirmTime: "Diese Uhrzeit bestätigen",
  confirmLegend: "Angebotene Uhrzeiten",
  counterOpen: "Andere Uhrzeit vorschlagen",
  counterTitle: "Andere Uhrzeit vorschlagen",
  counterLead: (max: number) => af(f, `Wählen Sie 1 bis ${max} andere Uhrzeiten.`, `Wähle 1 bis ${max} andere Uhrzeiten.`),
  counterSend: "Vorschlag senden",
  roundsLeft: (n: number) => (n === 1 ? "Noch 1 Runde zum Abstimmen." : `Noch ${n} Runden zum Abstimmen.`),
  noRounds: af(f, "Jetzt bitte eine Uhrzeit bestätigen oder absagen.", "Jetzt bitte eine Uhrzeit bestätigen oder absagen."),
  waitTitle: (name: string | null) => (name ? `${name} ist dran` : af(f, "Ihr Gegenüber ist dran", "Dein Gegenüber ist dran")),
  waitText: (when: string | null) =>
    af(
      f,
      when ? `Sie bekommen eine Nachricht, sobald eine Antwort da ist – spätestens ${when}.` : "Sie bekommen eine Nachricht, sobald eine Antwort da ist.",
      when ? `Du bekommst eine Nachricht, sobald eine Antwort da ist – spätestens ${when}.` : "Du bekommst eine Nachricht, sobald eine Antwort da ist.",
    ),
  yourTimes: af(f, "Ihre Uhrzeiten", "Deine Uhrzeiten"),

  declineOpen: "Ablehnen",
  declineTitle: "Vorschlag ablehnen?",
  declineText: (name: string | null) =>
    af(
      f,
      `${name ?? "Ihr Gegenüber"} erfährt nur, dass aus dem Vorschlag diesmal kein Abend wird – keinen Grund.`,
      `${name ?? "Dein Gegenüber"} erfährt nur, dass aus dem Vorschlag diesmal kein Abend wird – keinen Grund.`,
    ),
  reasonLegend: af(f, "Grund (freiwillig, nur für Fermata)", "Grund (freiwillig, nur für Fermata)"),
  reasons: {
    termin: "Keine der Uhrzeiten passt",
    krank: "Krank oder verhindert",
    kein_interesse: "Der Vorschlag passt nicht",
    lokal: "Das Lokal passt nicht",
    sicherheit: "Ich fühle mich unsicher",
    sonstiges: "Etwas anderes",
  } as Record<string, string>,
  reasonSafetyHint: af(f, "Wenn Sie etwas melden möchten, geht das jederzeit vertraulich.", "Wenn du etwas melden möchtest, geht das jederzeit vertraulich."),
  declineConfirm: "Ja, ablehnen",
  keep: "Abbrechen",
  declined: "Abgelehnt. Wir melden uns mit dem nächsten Vorschlag.",

  confirmedTitle: "Der Abend steht",
  confirmedWhen: (when: string) => when,
  addToCalendar: "In den Kalender",
  prepareTitle: "Vorbereiten",
  hintTitle: "Erkennungszeichen",
  hintLead: (name: string | null) =>
    af(
      f,
      `Freiwillig: Woran erkennt ${name ?? "Ihr Gegenüber"} Sie? Zum Beispiel „grüner Schal“. ${name ?? "Ihr Gegenüber"} sieht es erst 15 Minuten vor Beginn. Danach wird es gelöscht.`,
      `Freiwillig: Woran erkennt ${name ?? "dein Gegenüber"} dich? Zum Beispiel „grüner Schal“. ${name ?? "Dein Gegenüber"} sieht es erst 15 Minuten vor Beginn. Danach wird es gelöscht.`,
    ),
  hintLabel: "Erkennungszeichen",
  hintHint: (max: number) => `Höchstens ${max} Zeichen. Leer lassen löscht es.`,
  hintSave: "Speichern",
  hintSaved: "Gespeichert.",
  hintRemoved: "Entfernt.",
  safetyTitle: "Sicher unterwegs",
  shareLink: "Abend teilen",
  shareText: af(f, "Eine Vertrauensperson sieht, wo und wann Ihr Abend ist.", "Eine Vertrauensperson sieht, wo und wann dein Abend ist."),
  checkinLink: "Check-in",
  checkinText: "30 Minuten nach Beginn fragen wir kurz, ob alles in Ordnung ist.",
  reportLink: "Etwas melden",
  reportText: "Vertraulich. Das Gegenüber erfährt nie, wer gemeldet hat.",
  helpLink: "Hilfe und Notruf",

  cancelOpen: "Abend absagen",
  cancelTitle: "Abend absagen?",
  cancelEarly: (until: string) =>
    af(
      f,
      `Bis ${until} gilt die Absage als rechtzeitig: Sie und Ihr Gegenüber bekommen den Abend zurück.`,
      `Bis ${until} gilt die Absage als rechtzeitig: Du und dein Gegenüber bekommt den Abend zurück.`,
    ),
  cancelLate: af(
    f,
    "Der Abend ist in weniger als 24 Stunden. Eine Absage gilt jetzt als kurzfristig: Der Abend zählt für Sie als genutzt, Ihr Gegenüber bekommt ihn zurück.",
    "Der Abend ist in weniger als 24 Stunden. Eine Absage gilt jetzt als kurzfristig: Der Abend zählt für dich als genutzt, dein Gegenüber bekommt ihn zurück.",
  ),
  cancelLateFuture: (from: string) =>
    af(f, `Ab ${from} gilt eine Absage als kurzfristig und der Abend zählt für Sie als genutzt.`, `Ab ${from} gilt eine Absage als kurzfristig und der Abend zählt für dich als genutzt.`),
  cancelInfo: af(f, "Wir informieren Ihr Gegenüber und das Lokal. Einen Grund erfährt niemand außer Fermata.", "Wir informieren dein Gegenüber und das Lokal. Einen Grund erfährt niemand außer Fermata."),
  cancelSafety: af(f, "Fühlen Sie sich unsicher? Dann wählen Sie den Grund „Ich fühle mich unsicher“ – wir sehen uns das an.", "Fühlst du dich unsicher? Dann wähl den Grund „Ich fühle mich unsicher“ – wir sehen uns das an."),
  cancelConfirm: "Ja, absagen",
  cancelled: af(f, "Abgesagt. Wir haben Ihr Gegenüber und das Lokal informiert.", "Abgesagt. Wir haben dein Gegenüber und das Lokal informiert."),

  endedDeclined: (byMe: boolean) => (byMe ? af(f, "Sie haben den Vorschlag abgelehnt.", "Du hast den Vorschlag abgelehnt.") : "Aus diesem Vorschlag wird diesmal kein Abend."),
  endedLapsed: "Die Frist ist abgelaufen. Aus diesem Vorschlag wird kein Abend.",
  endedCancelled: (byMe: boolean) => (byMe ? af(f, "Sie haben den Abend abgesagt.", "Du hast den Abend abgesagt.") : "Der Abend findet nicht statt."),
  endedNext: af(f, "Wir melden uns mit dem nächsten Vorschlag.", "Wir melden uns mit dem nächsten Vorschlag."),

  // Finde-Fenster
  findTitle: af(f, "Ihr Gegenüber finden", "Dein Gegenüber finden"),
  findLead: af(
    f,
    "Von 15 Minuten vor bis 45 Minuten nach Beginn sehen Sie hier, woran Sie Ihr Gegenüber erkennen.",
    "Von 15 Minuten vor bis 45 Minuten nach Beginn siehst du hier, woran du dein Gegenüber erkennst.",
  ),
  findNow: "Jetzt im Lokal",
  findOpens: (when: string) => `Öffnet ${when}.`,
  findClosed: "Das Finde-Fenster ist geschlossen.",
  findAsk: (name: string) => af(f, `Fragen Sie im Lokal nach dem Tisch für „${name}“.`, `Frag im Lokal nach dem Tisch für „${name}“.`),
  findCounterpart: (name: string | null) => name ?? af(f, "Ihr Gegenüber", "Dein Gegenüber"),
  findCounterpartHint: "Erkennungszeichen",
  findNoHint: "Kein Erkennungszeichen hinterlegt.",
  findMyHint: af(f, "Ihr Erkennungszeichen", "Dein Erkennungszeichen"),
  findOpenCta: "Finde-Fenster öffnen",

  // Rückmeldung
  feedbackTitle: af(f, "Wie war Ihr Abend?", "Wie war dein Abend?"),
  feedbackLead: af(
    f,
    "Ihre Rückmeldung sieht nur Fermata, nie Ihr Gegenüber. Sie hilft uns, beim nächsten Mal besser vorzuschlagen.",
    "Deine Rückmeldung sieht nur Fermata, nie dein Gegenüber. Sie hilft uns, beim nächsten Mal besser vorzuschlagen.",
  ),
  feedbackOpenUntil: (when: string) => `Möglich ${when}.`,
  feedbackCta: "Rückmeldung geben",
  feedbackNotYet: (when: string) => af(f, `Die Rückmeldung ist ab Beginn des Abends möglich (${when}).`, `Die Rückmeldung ist ab Beginn des Abends möglich (${when}).`),
  feedbackClosed: "Die Zeit für eine Rückmeldung ist vorbei.",
  feedbackThanks: "Danke für die Rückmeldung.",
  attendedLegend: af(f, "Waren Sie dort?", "Warst du dort?"),
  yes: "Ja",
  no: "Nein",
  otherAttendedLegend: (name: string | null) => `War ${name ?? af(f, "Ihr Gegenüber", "dein Gegenüber")} da?`,
  feltSafeLegend: af(f, "Haben Sie sich sicher gefühlt?", "Hast du dich sicher gefühlt?"),
  feltSafeNo: af(f, "Danke, dass Sie es sagen. Wir melden uns bei Ihnen. Möchten Sie etwas melden?", "Danke, dass du es sagst. Wir melden uns bei dir. Möchtest du etwas melden?"),
  meetAgainLegend: (name: string | null) => af(f, `Würden Sie ${name ?? "Ihr Gegenüber"} gern wiedersehen?`, `Würdest du ${name ?? "dein Gegenüber"} gern wiedersehen?`),
  meetAgain: { ja: "Ja", vielleicht: "Vielleicht", nein: "Nein" } as Record<string, string>,
  venueRatingLegend: "Wie war das Lokal?",
  matchQualityLegend: af(f, "Wie gut passte der Vorschlag?", "Wie gut passte der Vorschlag?"),
  ratingLabels: ["gar nicht", "wenig", "geht so", "gut", "sehr gut"],
  ratingOptional: "freiwillig",
  noteLabel: "Notiz für Fermata",
  noteHint: "Freiwillig, höchstens 2000 Zeichen. Nur Fermata liest sie.",
  contactLegend: af(f, "Möchten Sie Kontaktdaten tauschen?", "Möchtest du Kontaktdaten tauschen?"),
  contactLead: (name: string | null) =>
    af(
      f,
      `Nur wenn ${name ?? "Ihr Gegenüber"} auch Ja sagt, sehen Sie beide, was der andere freigibt. Ein Nein erfährt niemand.`,
      `Nur wenn ${name ?? "dein Gegenüber"} auch Ja sagt, seht ihr beide, was der andere freigibt. Ein Nein erfährt niemand.`,
    ),
  contactYes: "Ja, Kontakt teilen",
  contactNo: "Nein, danke",
  shareWhat: af(f, "Was möchten Sie teilen?", "Was möchtest du teilen?"),
  shareEmail: "E-Mail-Adresse",
  sharePhone: "Telefonnummer",
  noPhone: af(f, "Keine Telefonnummer hinterlegt. Sie können sie im Konto ergänzen.", "Keine Telefonnummer hinterlegt. Du kannst sie im Konto ergänzen."),
  contactConsentTitle: "Einwilligung zum Kontakttausch",
  contactConsentLead: af(
    f,
    "Für den Kontakttausch brauchen wir einmal Ihre Einwilligung. Danach können Sie hier wählen.",
    "Für den Kontakttausch brauchen wir einmal deine Einwilligung. Danach kannst du hier wählen.",
  ),
  contactConsentAgree: "Ich habe den Text gelesen und willige ein.",
  contactConsentRead: "Ganzen Text lesen",
  feedbackSubmit: "Rückmeldung senden",
  feedbackRequired: af(f, "Bitte sagen Sie uns, ob Sie dort waren.", "Bitte sag uns, ob du dort warst."),
  shareRequired: "Bitte E-Mail, Telefon oder beides wählen.",

  // Kontakt
  contactTitle: "Kontakt",
  contactReleasedTitle: (name: string | null) => (name ? `${name} möchte auch Kontakt` : af(f, "Sie möchten beide Kontakt", "Ihr möchtet beide Kontakt")),
  contactReleasedText: af(f, "Sie haben beide Ja gesagt. Das hat Ihr Gegenüber freigegeben:", "Ihr habt beide Ja gesagt. Das hat dein Gegenüber freigegeben:"),
  contactMine: af(f, "Sie haben freigegeben:", "Du hast freigegeben:"),
  contactPending: af(
    f,
    "Ihr Ja ist gespeichert. Sagt Ihr Gegenüber innerhalb von 7 Tagen nach dem Abend auch Ja, sehen Sie hier die Kontaktdaten.",
    "Dein Ja ist gespeichert. Sagt dein Gegenüber innerhalb von 7 Tagen nach dem Abend auch Ja, siehst du hier die Kontaktdaten.",
  ),
  contactClosed: "Der Kontakttausch für diesen Abend ist abgeschlossen.",
  contactNone: af(f, "Sie haben keinen Kontakttausch gewählt.", "Du hast keinen Kontakttausch gewählt."),
  contactNoteApp: "Kontaktdaten stehen nur hier in der App, nie in einer E-Mail.",
  email: "E-Mail",
  phone: "Telefon",
  contactCta: "Kontaktdaten ansehen",

  // Nachbesprechung
  debriefTitle: "Nachbesprechung mit Viola",
  debriefText: (minutes: number, until: string) =>
    af(
      f,
      `Etwa ${minutes} Minuten: Wie war der Abend, und was soll beim nächsten Vorschlag anders sein? Möglich ${until}.`,
      `Etwa ${minutes} Minuten: Wie war der Abend, und was soll beim nächsten Vorschlag anders sein? Möglich ${until}.`,
    ),
  debriefCta: "Nachbesprechung beginnen",
  debriefDone: "Die Nachbesprechung ist abgeschlossen.",

  // Fehler (hint)
  errors: {
    invalid_state: "Das geht gerade nicht mehr. Die Seite zeigt jetzt den aktuellen Stand.",
    invalid_times: (max: number) => `Bitte 1 bis ${max} verschiedene Uhrzeiten wählen.`,
    time_too_soon: "Diese Uhrzeit liegt zu kurzfristig. Bitte eine spätere wählen.",
    time_not_allowed: "Diese Uhrzeit ist nicht wählbar.",
    time_not_offered: "Diese Uhrzeit wurde nicht angeboten.",
    no_table_free: "Zu dieser Uhrzeit ist im Lokal leider kein Tisch mehr frei. Bitte eine andere Uhrzeit wählen.",
    no_venue: "Für diesen Abend ist noch kein Lokal festgelegt. Wir kümmern uns darum.",
    venue_inactive: "Das Lokal nimmt gerade keine Reservierungen an. Wir melden uns.",
    account_suspended: af(f, "Ihr Konto ist gerade gesperrt.", "Dein Konto ist gerade gesperrt."),
    evening_on_hold: "Dieser Abend ist gerade angehalten. Wir melden uns.",
    not_your_turn: "Jetzt ist das Gegenüber an der Reihe.",
    max_rounds: "Jetzt bitte eine der Uhrzeiten bestätigen oder absagen.",
    invalid_reason: "Bitte einen der Gründe wählen.",
    evening_started: "Der Abend hat schon begonnen. Absagen geht nicht mehr; bei Problemen hilft die Hilfe-Seite.",
    find_window_closed: "Das Finde-Fenster ist vorbei.",
    hint_too_long: "Das Erkennungszeichen ist zu lang.",
    feedback_not_open: "Die Rückmeldung ist gerade nicht möglich.",
    already_submitted: "Die Rückmeldung ist schon gespeichert.",
    invalid_input: af(f, "Bitte sagen Sie uns, ob Sie dort waren.", "Bitte sag uns, ob du dort warst."),
    invalid_rating: "Bewertungen gehen von 1 bis 5.",
    text_too_long: "Die Notiz ist zu lang (höchstens 2000 Zeichen).",
    consent_missing: "Für den Kontakttausch fehlt noch die Einwilligung.",
    version_mismatch: "Der Text der Einwilligung wurde gerade geändert. Bitte die Seite neu laden und noch einmal lesen.",
    consent_required: af(f, "Bitte setzen Sie das Häkchen bei der Einwilligung, oder wählen Sie „Nein, danke“.", "Bitte setz das Häkchen bei der Einwilligung, oder wähl „Nein, danke“."),
    nothing_to_share: "Bitte E-Mail, Telefon oder beides wählen.",
    no_phone: "Es ist keine Telefonnummer hinterlegt.",
    no_evening_available: af(
      f,
      "Der Abend lässt sich gerade nicht bestätigen: In einer der Mitgliedschaften ist kein Abend frei. Sehen Sie bitte unter Mitgliedschaft nach; wir melden uns.",
      "Der Abend lässt sich gerade nicht bestätigen: In einer der Mitgliedschaften ist kein Abend frei. Sieh bitte unter Mitgliedschaft nach; wir melden uns.",
    ),
    no_membership_row: "Der Abend lässt sich gerade nicht bestätigen. Wir kümmern uns darum und melden uns.",
    suspended: "Dieser Abend ist gerade angehalten. Wir melden uns.",
    not_participant: "Diesen Abend gibt es nicht.",
    generic: af(f, "Das hat nicht geklappt. Bitte versuchen Sie es gleich noch einmal.", "Das hat nicht geklappt. Bitte versuch es gleich noch einmal."),
  } as Record<string, string | ((max: number) => string)>,
  notFoundTitle: "Diesen Abend gibt es nicht",
  notFoundText: af(f, "Vielleicht ist der Link alt. In der Übersicht finden Sie alle Ihre Abende.", "Vielleicht ist der Link alt. In der Übersicht findest du alle deine Abende."),
});

/** Karten „Nächster Schritt“ auf der Startseite. */
export const startCards = (f: AddressForm) => ({
  eyebrow: "Nächster Schritt",
  answerBy: (when: string) => `Antwort ${when}.`,
  conversation: {
    title: "Gespräch mit Viola",
    text: af(f, "Viola lernt Sie in einem ruhigen Gespräch kennen – mit Stimme oder als Text.", "Viola lernt dich in einem ruhigen Gespräch kennen – mit Stimme oder als Text."),
    cta: "Zum Gespräch",
  },
  summary: {
    title: af(f, "Ihre Zusammenfassung", "Deine Zusammenfassung"),
    text: af(f, "Viola hat das Gespräch zusammengefasst. Bitte lesen und bestätigen Sie es.", "Viola hat das Gespräch zusammengefasst. Bitte lies und bestätige es."),
    cta: "Zusammenfassung lesen",
  },
  availability: {
    title: "Freie Abende eintragen",
    text: (until: string) => af(f, `Wann haben Sie in den nächsten zwei Wochen Zeit? Bitte ${until}.`, `Wann hast du in den nächsten zwei Wochen Zeit? Bitte ${until}.`),
    cta: "Freie Abende eintragen",
  },
  evening: {
    choose_time: { title: (name: string | null) => (name ? `Ein Vorschlag: Abend mit ${name}` : "Ein Vorschlag für einen Abend"), cta: "Uhrzeit wählen" },
    answer_time: { title: (name: string | null) => (name ? `${name} hat Uhrzeiten vorgeschlagen` : "Uhrzeiten zum Bestätigen"), cta: "Uhrzeit bestätigen" },
    find: { title: (name: string | null) => (name ? `Gleich: Abend mit ${name}` : "Gleich beginnt der Abend"), cta: "Finde-Fenster öffnen" },
    feedback: { title: () => af(f, "Wie war Ihr Abend?", "Wie war dein Abend?"), cta: "Rückmeldung geben" },
    contact: { title: () => "Kontaktdaten freigegeben", cta: "Kontakt ansehen" },
    debrief: { title: () => "Nachbesprechung mit Viola", cta: "Nachbesprechung beginnen" },
    prepare: { title: (name: string | null) => (name ? `Abend mit ${name}` : af(f, "Ihr nächster Abend", "Dein nächster Abend")), cta: "Zum Abend" },
    wait: { title: (name: string | null) => (name ? `${name} ist dran` : "Das Gegenüber ist dran"), cta: "Zum Abend" },
  } as Record<string, { title: (name: string | null) => string; cta: string }>,
  waiting: {
    title: "Alles erledigt",
    text: af(f, "Wir melden uns mit dem nächsten Vorschlag, per E-Mail und, wenn Sie möchten, als Mitteilung.", "Wir melden uns mit dem nächsten Vorschlag, per E-Mail und, wenn du möchtest, als Mitteilung."),
    cta: "Mitteilungen einrichten",
  },
  eveningsTitle: "Abende",
  eveningsNext: (when: string, name: string | null) => (name ? `Nächster Abend: ${when} mit ${name}` : `Nächster Abend: ${when}`),
  eveningsNone: "Noch kein Abend geplant.",
  eveningsCta: "Zu den Abenden",
});
