// Admin „Mitgliedschaft“: Erklärungen (Bestellung, Kündigung, Widerruf) und Kontingent-Korrektur.

export const adminMembership = {
  title: "Mitgliedschaft",
  lead: "Bestellungen, Kündigungen und Widerrufe mit Zeitpunkt und Eingangsbestätigung. Korrekturen am Kontingent einer Person.",
  actions: {
    title: "Erklärungen",
    filterLabel: "Art",
    all: "alle",
    kinds: { order: "Bestellung", cancel: "Kündigung", withdraw: "Widerruf" } as Record<string, string>,
    empty: "Noch keine Erklärungen.",
    cols: { at: "Eingang", kind: "Art", contract: "Vertrag", person: "Person", effective: "Wirksam", confirmation: "Bestätigung", result: "Ergebnis" },
    confirmationSent: (d: string) => `per Mail ${d}`,
    confirmationMissing: "noch nicht verschickt",
    deletedPerson: "Konto gelöscht",
    refund: (s: string) => `Erstattung: ${s}`,
    tier: (s: string) => `Stufe ${s}`,
    stripe: (s: string) => `Stripe: ${s}`,
  },
  ledger: {
    title: "Kontingent korrigieren",
    lead: "Gutschrift oder Abzug von Abenden für eine Person. Jede Korrektur braucht eine Begründung und steht im Audit-Protokoll.",
    search: "Person suchen",
    searchLabel: "E-Mail, Name oder Postleitzahl",
    searchSubmit: "Suchen",
    results: "Treffer",
    noResults: "Keine Person gefunden.",
    choose: "Auswählen",
    person: "Person",
    membership: "Mitgliedschaft",
    available: "Verfügbare Abende",
    entries: "Buchungen",
    noEntries: "Keine Buchungen.",
    cols: { at: "Zeit", kind: "Art", amount: "Abende", expires: "Verfällt", note: "Notiz" },
    kinds: {
      free_grant: "Gratis-Abend",
      period_grant: "Zuteilung",
      reserve: "gebunden",
      release: "zurück",
      use: "genutzt",
      credit: "Gutschrift",
      expire: "verfallen",
      adjust: "Korrektur",
    } as Record<string, string>,
    amount: "Abende (+ Gutschrift, − Abzug)",
    amountHint: "Ganze Zahl zwischen −20 und 20, nicht 0.",
    note: "Begründung (Pflicht)",
    expiresAt: "Verfällt am (nur bei Gutschrift, freiwillig)",
    submit: "Korrektur buchen",
    dialogTitle: "Korrektur buchen?",
    dialogText: "Die Buchung lässt sich nicht löschen, nur mit einer weiteren Korrektur ausgleichen.",
    confirm: "Buchen",
    done: "Gebucht.",
    toAccount: "Zum Konto",
  },
  errors: {
    invalid_input: "Bitte eine Zahl zwischen −20 und 20 (nicht 0) und eine Begründung mit mindestens 3 Zeichen angeben.",
    would_be_negative: "Das Kontingent darf nicht negativ werden.",
  } as Record<string, string>,
};
