// Admin „Lokale & Plätze“: Lokale pflegen, Plätze anlegen, Zeiträume, Abende klären.

export const adminVenues = {
  title: "Lokale & Plätze",
  lead: "Partner-Lokale, freie Tische je Uhrzeit, Zeiträume der Zeitenabfrage und Abende, deren Ergebnis offen ist.",
  sub: { venues: "Lokale", periods: "Zeiträume", evenings: "Abende klären" },
  list: {
    title: "Lokale",
    add: "Neues Lokal",
    showInactive: "Auch inaktive zeigen",
    showActive: "Nur aktive zeigen",
    empty: "Noch keine Lokale.",
    cols: { name: "Lokal", place: "Ort", mode: "Reservierung", contact: "Kontakt", slots: "Plätze (kommend)", free: "freie Tische", reservations: "Reservierungen", state: "Stand" },
    active: "aktiv",
    inactive: "inaktiv",
  },
  modes: { email: "per E-Mail", telefon: "per Telefon", manuell: "von Hand" } as Record<string, string>,
  form: {
    newTitle: "Neues Lokal",
    editTitle: (n: string) => `Lokal: ${n}`,
    back: "Alle Lokale",
    basics: "Lokal",
    name: "Name",
    street: "Straße und Hausnummer",
    postalCode: "Postleitzahl",
    city: "Ort",
    cityHint: "Leer lassen: Ort aus der Postleitzahl.",
    lat: "Breitengrad",
    lon: "Längengrad",
    coordsHint: "Leer lassen: Mittelpunkt der Postleitzahl (GeoNames). Genauer ist der Wert aus einer Karte.",
    contact: "Kontakt und Reservierung",
    contactName: "Ansprechperson",
    contactEmail: "E-Mail für Reservierungen",
    contactPhone: "Telefon",
    mode: "Reservierung",
    modeHint: "Per E-Mail: das Lokal bekommt die Reservierung und bestätigt mit einem Klick. Per Telefon oder von Hand: Benn bekommt die Mail und ruft an.",
    guests: "Für die Gäste",
    description: "Beschreibung",
    accessibility: "Barrierefreiheit",
    accessibilityHint: "Zum Beispiel stufenloser Eingang, barrierefreies WC.",
    transport: "Anfahrt mit Bus und Bahn",
    agreement: "Vereinbarung (Frage B10)",
    reservationNote: "Hinweis in der Reservierungs-Mail",
    reservationNoteHint: "Steht in jeder Reservierungs-Mail an das Lokal.",
    agreementNotes: "Absprachen (intern)",
    agreementNotesHint: "Zum Beispiel Getränk zur Begrüßung, Tisch für die Loge, Einweisung des Personals.",
    agreementBriefed: "Personal eingewiesen (Sicherheitsstandard 14)",
    optional: "freiwillig",
    create: "Lokal anlegen",
    save: "Änderungen speichern",
    created: "Lokal angelegt.",
    saved: "Gespeichert.",
    coords: (lat: string, lon: string) => `Koordinaten ${lat}, ${lon}`,
  },
  active: {
    title: "Stand",
    isActive: "Das Lokal ist aktiv und nimmt Reservierungen an.",
    isInactive: "Das Lokal ist inaktiv und nimmt keine neuen Reservierungen an.",
    deactivate: "Deaktivieren",
    activate: "Wieder aktivieren",
    dialogTitle: "Lokal deaktivieren?",
    dialogText: "Neue Reservierungen sind dann nicht mehr möglich. Bestehende bleiben bestehen und müssen bei Bedarf einzeln abgesagt werden.",
    confirm: "Deaktivieren",
    done: (n: number) => (n > 0 ? `Gespeichert. Es gibt noch ${n} kommende Reservierungen.` : "Gespeichert."),
  },
  slots: {
    title: "Plätze anlegen",
    lead: "Ortszeit Europe/Berlin, auch über die Zeitumstellung. Vergangene Zeiten werden übersprungen.",
    firstDay: "Erster Tag",
    weeks: "Wochen",
    weekdays: "Wochentage",
    weekdayNames: ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
    times: "Uhrzeiten",
    timesHint: "Mit Komma getrennt, zum Beispiel 19:00, 19:30, 20:00.",
    tables: "Tische je Uhrzeit",
    update: "Bestehende Plätze auf diese Tischzahl setzen",
    submit: "Plätze anlegen",
    done: (c: number, u: number, s: number) => `${c} angelegt, ${u} geändert, ${s} übersprungen.`,
    listTitle: "Plätze der nächsten Wochen",
    empty: "Keine kommenden Plätze.",
    cols: { when: "Zeit", tables: "Tische", reserved: "reserviert", free: "frei", reservations: "Reservierungen", action: "Aktion" },
    reservation: (code: string) => `Tisch ${code}`,
    resStatus: { reserved: "reserviert", cancelled: "abgesagt" } as Record<string, string>,
    notified: "Mail verschickt",
    confirmed: "vom Lokal bestätigt",
    unconfirmed: "noch nicht bestätigt",
    setTables: "Tische",
    setTablesSubmit: "Ändern",
    delete: "Löschen",
    deleteTitle: "Platz löschen?",
    deleteText: "Der Platz wird entfernt. Das geht nur ohne Reservierung.",
    deleteConfirm: "Löschen",
    deleted: "Gelöscht.",
    updated: "Geändert.",
  },
  periods: {
    title: "Zeiträume",
    lead: "Alle 14 Tage legt ein Zeitplan den nächsten Zeitraum an und fragt die freien Zeiten ab. Hier lässt sich ein Zeitraum von Hand anlegen.",
    createTitle: "Zeitraum anlegen",
    startsOn: "Beginn (leer: der nächste fällige)",
    notify: "Mitglieder sofort nach ihren freien Zeiten fragen",
    submit: "Zeitraum anlegen",
    done: "Zeitraum angelegt.",
    empty: "Noch keine Zeiträume.",
    cols: { period: "Zeitraum", ask: "Abfrage ab", until: "Antworten bis", people: "Personen mit Zeiten", runs: "Läufe" },
    noRuns: "noch kein Lauf",
  },
  evenings: {
    title: "Abende klären",
    lead: "Bestätigte Abende in der Vergangenheit, bei denen das Ergebnis nicht automatisch feststeht.",
    empty: "Kein Abend wartet auf eine Entscheidung.",
    reasons: {
      bestritten: "Nichterscheinen bestritten",
      meldung: "offene Meldung",
      ueberfaellig: "seit über 48 Stunden ohne Ergebnis",
    } as Record<string, string>,
    feedback: "Rückmeldungen",
    noFeedback: "Noch keine Rückmeldung.",
    attended: (name: string, me: boolean | null, other: boolean | null) =>
      `${name}: selbst ${me ? "da" : "nicht da"}, Gegenüber ${other === null ? "keine Angabe" : other ? "da" : "nicht da"}`,
    outcome: "Ergebnis",
    happened: "Stattgefunden",
    noShow: (n: string) => `${n} nicht erschienen`,
    noShowBoth: "Beide nicht erschienen",
    note: "Notiz (intern)",
    submit: "Ergebnis festlegen",
    dialogTitle: "Ergebnis festlegen?",
    dialogText: "Das Ergebnis bestimmt das Kontingent beider Personen (Nichterscheinen verbraucht den Abend).",
    confirm: "Festlegen",
    done: "Ergebnis festgelegt.",
    flagOutcome: (o: string) => `Ergebnis von Hand festgelegt: ${o === "happened" ? "stattgefunden" : "nicht erschienen"}`,
    openReports: (n: number) => (n === 1 ? "1 offene Meldung zu diesem Abend" : `${n} offene Meldungen zu diesem Abend`),
  },
  errors: {
    unknown_field: "Unbekanntes Feld.",
    invalid_name: "Bitte einen Namen angeben (höchstens 120 Zeichen).",
    invalid_street: "Bitte Straße und Hausnummer angeben.",
    invalid_postal_code: "Bitte eine fünfstellige Postleitzahl angeben.",
    invalid_city: "Bitte einen Ort angeben.",
    invalid_coordinates: "Koordinaten fehlen oder liegen nicht in Deutschland. Bitte prüfen oder leer lassen.",
    invalid_email: "Bitte eine gültige E-Mail-Adresse angeben.",
    invalid_reservation_mode: "Bitte eine Reservierungsart wählen.",
    email_required: "Für Reservierungen per E-Mail fehlt die Adresse.",
    invalid_agreement: "Ungültige Vereinbarung.",
    text_too_long: "Ein Text ist zu lang.",
    venue_not_found: "Lokal nicht gefunden.",
    invalid_range: "Bitte einen ersten Tag und 1 bis 26 Wochen angeben.",
    invalid_weekdays: "Bitte mindestens einen Wochentag wählen.",
    invalid_times: "Uhrzeiten bitte als HH:MM, höchstens 12.",
    invalid_tables: "Tische zwischen 0 und 50.",
    below_reserved: "Weniger Tische als schon reserviert.",
    slot_not_found: "Platz nicht gefunden.",
    slot_reserved: "Der Platz hat Reservierungen und lässt sich nicht löschen.",
    period_exists: "Diesen Zeitraum gibt es schon.",
    evening_not_found: "Abend nicht gefunden.",
    invalid_state: "Nur bestätigte Abende lassen sich so entscheiden.",
    invalid_outcome: "Bitte ein Ergebnis wählen.",
    invalid_user: "Diese Person gehört nicht zu diesem Abend.",
  } as Record<string, string>,
};
