// Admin „Sicherheit“: Meldungen (Ziel 24 Stunden), Sanktionen, Widersprüche, Hinweise, Polizeivorlage, Transkript.

export const adminSafety = {
  title: "Sicherheit",
  lead: "Meldungen nach Dringlichkeit und Frist. Ziel: jede Meldung innerhalb von 24 Stunden prüfen.",
  sub: {
    reports: "Meldungen",
    flags: "Hinweise",
    appeals: "Widersprüche",
    sanctions: "Sanktionen",
  },
  reports: {
    title: "Meldungen",
    showOpen: "Offene",
    showResolved: "Erledigt",
    showDismissed: "Verworfen",
    filterLabel: "Meldungen zeigen",
    empty: "Keine Meldungen in dieser Ansicht.",
    cols: {
      due: "Frist",
      severity: "Stufe",
      category: "Art",
      context: "Bereich",
      reported: "Gemeldet",
      reporter: "Meldet",
      status: "Stand",
      created: "Eingang",
    },
    noRelation: "ohne Beziehung",
    prior: (n: number) => (n === 1 ? "1 frühere Meldung" : `${n} frühere Meldungen`),
    activeSanction: (k: string) => `aktiv: ${k}`,
  },
  status: { open: "offen", in_review: "in Prüfung", resolved: "erledigt", dismissed: "verworfen" } as Record<string, string>,
  contexts: {
    abend: "Abend",
    termin: "Termin",
    gespraech: "Gespräch",
    rueckmeldung: "Rückmeldung",
    konto: "Konto",
    sonstiges: "Sonstiges",
  } as Record<string, string>,
  sanctionKinds: {
    hinweis: "Hinweis",
    vorlaeufige_sperre: "Vorläufige Sperre",
    sperre: "Sperre",
    ausschluss: "Ausschluss",
  } as Record<string, string>,
  report: {
    back: "Alle Meldungen",
    title: (label: string) => `Meldung: ${label}`,
    facts: "Meldung",
    context: "Bereich",
    received: "Eingang",
    due: "Frist",
    resolved: "Abgeschlossen",
    resolution: "Begründung",
    description: "Schilderung (Wortlaut)",
    noDescription: "Keine Schilderung.",
    wantsContact: "Rückmeldung an die meldende Person gewünscht",
    related: "Beziehung über Fermata",
    relatedNo: "Keine Beziehung über Fermata. Darum keine automatische Sperre.",
    people: "Beteiligte",
    reporter: "Meldende Person",
    reported: "Gemeldete Person",
    accountStatus: "Kontostand",
    reporterHidden: "Die gemeldete Person erfährt nie, wer gemeldet hat.",
    evening: "Abend",
    noEvening: "Kein Abend angegeben.",
    eveningState: "Stand",
    eveningStart: "Beginn",
    venue: "Lokal",
    events: "Verlauf des Abends",
    checkins: "Check-ins",
    checkinStatus: { gut: "alles gut", unsicher: "unsicher", hilfe: "Hilfe" } as Record<string, string>,
    history: "Vorgeschichte der gemeldeten Person",
    priorReports: "Frühere Meldungen",
    sanctions: "Sanktionen",
    flags: "Hinweise zu dieser Meldung",
    none: "Keine.",
    since: "seit",
    until: "bis",
    lifted: "aufgehoben",
    actions: "Entscheiden",
    takeReview: "In Prüfung nehmen",
    takeReviewDone: "Die Meldung ist in Prüfung.",
    decideTitle: "Meldung abschließen",
    decision: "Entscheidung",
    decisions: { resolved: "Erledigt (Meldung bestätigt, Maßnahme getroffen)", dismissed: "Verwerfen (kein Verstoß)" } as Record<string, string>,
    resolutionLabel: "Begründung (intern)",
    resolutionHint: "Die meldende Person bekommt nur eine Abschluss-Mail ohne Einzelheiten.",
    liftProvisional: "Vorläufige Sperre aus dieser Meldung aufheben",
    liftProvisionalHint: "Beim Verwerfen voreingestellt. Bei „Erledigt“ bleibt sie, bis eine Sanktion sie ersetzt.",
    decide: "Abschließen",
    decided: (lifted: number) => (lifted > 0 ? "Abgeschlossen. Die vorläufige Sperre ist aufgehoben." : "Abgeschlossen."),
    closed: "Diese Meldung ist abgeschlossen.",
    police: "Vorlage für eine Polizeimeldung",
    policeLink: "Vorlage öffnen",
    policeHint: "Entwurf mit den vorhandenen Fakten. Ob Anzeige erstattet wird, entscheidet Benn, nicht das System.",
  },
  sanction: {
    title: "Sanktion verhängen",
    for: (name: string) => `Für ${name}`,
    kind: "Art",
    kinds: {
      hinweis: "Hinweis (nur Mitteilung)",
      sperre: "Sperre (befristet oder unbefristet)",
      ausschluss: "Ausschluss (dauerhaft, Sperrliste)",
    } as Record<string, string>,
    reason: "Begründung (sieht die Person)",
    reasonHint: "Keine Angaben zur meldenden Person.",
    endsAt: "Ende der Sperre",
    endsAtHint: "Leer lassen für eine unbefristete Sperre. Nur bei „Sperre“.",
    exclusionNote:
      "Ausschluss: Das Konto bleibt gesperrt. Name und Geburtsdatum kommen als Hash auf die Sperrliste, dazu der Hash des Ausweises, wenn er bei der Prüfung gespeichert wurde. Eine neue Anmeldung mit demselben Ausweis wird automatisch gesperrt, ein Namens-Treffer erzeugt nur einen Hinweis.",
    provisionalNote: "Eine vorläufige Sperre entsteht automatisch bei Null-Toleranz-Meldungen. Sperre und Ausschluss ersetzen sie.",
    submit: "Sanktion verhängen",
    dialogTitle: "Sanktion verhängen?",
    dialogText: "Die Person bekommt eine Mail mit der Begründung. Bei Sperre und Ausschluss werden offene Abende abgesagt.",
    confirm: "Verhängen",
    done: (cancelled: number) => (cancelled > 0 ? `Verhängt. ${cancelled} Abende abgesagt.` : "Verhängt."),
    docHashMissing: "Der Hash des Ausweises fehlt. Bitte aus der Ausweisprüfung nachtragen (Hinweis steht auf der Sperrliste).",
    newTitle: "Sanktion verhängen",
    newLead: "Für eine Person ohne Bezug auf eine Meldung. Sonst bitte aus der Meldung heraus.",
    personMissing: "Keine Person gewählt. Bitte über Konten eine Person auswählen.",
  },
  lift: {
    title: "Aufheben",
    reason: "Begründung",
    submit: "Sanktion aufheben",
    dialogTitle: "Sanktion aufheben?",
    dialogText: "Das Konto bekommt seinen vorigen Stand zurück. Bei einem Ausschluss wird der Eintrag auf der Sperrliste gelöscht.",
    confirm: "Aufheben",
    done: "Aufgehoben.",
    notActive: "Diese Sanktion ist nicht mehr aktiv.",
  },
  sanctions: {
    title: "Sanktionen",
    lead: "Aktive Sanktionen. Befristete Sperren enden automatisch.",
    showActive: "Aktive",
    showAll: "Alle",
    filterLabel: "Sanktionen zeigen",
    empty: "Keine Sanktionen in dieser Ansicht.",
    cols: { person: "Person", kind: "Art", reason: "Begründung", since: "Seit", until: "Bis", report: "Meldung", appeal: "Widerspruch", action: "Aktion" },
    open: "Meldung",
    noEnd: "unbefristet",
    appealStatus: { open: "offen", accepted: "angenommen", rejected: "abgelehnt" } as Record<string, string>,
  },
  appeals: {
    title: "Widersprüche",
    lead: "Die Person bekommt die Entscheidung mit Begründung per Mail. Angenommen hebt die Sanktion auf.",
    showOpen: "Offene",
    showAll: "Alle",
    filterLabel: "Widersprüche zeigen",
    empty: "Keine Widersprüche in dieser Ansicht.",
    received: "Eingang",
    sanction: "Sanktion",
    text: "Widerspruch (Wortlaut)",
    decision: "Entscheidung",
    decisions: { accepted: "Annehmen (Sanktion aufheben)", rejected: "Ablehnen (Sanktion bleibt)" } as Record<string, string>,
    note: "Begründung (bekommt die Person per Mail)",
    submit: "Entscheiden",
    dialogTitle: "Widerspruch entscheiden?",
    dialogText: "Die Person bekommt die Entscheidung mit dieser Begründung per Mail.",
    confirm: "Entscheiden",
    done: (lifted: boolean) => (lifted ? "Entschieden. Die Sanktion ist aufgehoben." : "Entschieden."),
    decidedAt: (d: string) => `Entschieden ${d}`,
  },
  flags: {
    title: "Sicherheits-Hinweise",
    lead: "Hinweise des Sicherheits-Agenten, der Sperrliste, aus Meldungen, Check-ins und Rückmeldungen.",
    showOpen: "Offene",
    showAll: "Alle",
    filterLabel: "Hinweise zeigen",
    empty: "Keine offenen Hinweise.",
    cols: { severity: "Dringlichkeit", kind: "Art", person: "Person", source: "Quelle", context: "Bezug", created: "Seit", reviewed: "Erledigt", action: "Aktion" },
    sources: { agent: "Sicherheits-Agent", blocklist_name: "Sperrliste", report: "Meldung", system: "System", admin: "Admin" } as Record<string, string>,
    kinds: {
      sperrliste_ausweis: "Ausweis auf der Sperrliste (gesperrt)",
      sperrliste_name: "Name auf der Sperrliste (Verdacht)",
      minderjaehrig: "Laut Ausweis minderjährig",
      konto_geloescht_waehrend_pruefung: "Konto während einer Prüfung gelöscht",
      krise: "Krise im Gespräch",
      gewalt: "Gewalt im Gespräch",
      belaestigung: "Belästigung im Gespräch",
      sonstiges: "Sonstiges",
      no_show_bestritten: "Nichterscheinen bestritten",
      rueckmeldung_unsicher: "Rückmeldung: nicht sicher gefühlt",
      checkin_hilfe: "Check-in: Hilfe",
      checkin_unsicher: "Check-in: unsicher",
      meldung: "Neue Meldung",
      vorlaeufige_sperre: "Vorläufige Sperre (automatisch)",
      widerspruch: "Widerspruch eingelegt",
      wiederholt_nicht_erschienen: "Wiederholt nicht erschienen",
    } as Record<string, string>,
    session: "Gespräch",
    evening: "Abend",
    report: "Meldung",
    outcome: "Ergebnis",
    outcomeHint: "Kurz, für das Protokoll (z. B. „geprüft, kein Handlungsbedarf“).",
    review: "Erledigt",
    reviewDone: "Als erledigt vermerkt.",
    reviewedWith: (o: string) => `Ergebnis: ${o}`,
  },
  police: {
    title: "Vorlage für eine Polizeimeldung",
    back: "Zur Meldung",
    decide: "Ob Anzeige erstattet wird, entscheidet Benn – nach Rücksprache mit der betroffenen Person. Fermata erstattet nichts automatisch. Bei akuter Gefahr: 110.",
    draft: "ENTWURF. Platzhalter in [ECKIGEN KLAMMERN] ergänzen oder streichen.",
    textLabel: "Text der Vorlage",
    copy: "Text kopieren",
    logged: "Der Abruf dieser Vorlage steht im Audit-Protokoll.",
  },
  transcript: {
    title: "Gespräche mit Viola",
    lead: "Nur bei einem offenen Sicherheitsfall zu dieser Person. Erst die Liste, dann einzeln mit Begründung.",
    list: "Gespräche anzeigen",
    listing: "Wird geladen …",
    noSessions: "Keine Gespräche dieser Person.",
    cols: { kind: "Art", mode: "Form", when: "Zeit", end: "Ende", transcript: "Transkript" },
    kinds: { erstgespraech: "Erstgespräch", vertiefung: "Vertiefung", nachbesprechung: "Nachbesprechung", korrektur: "Korrektur" } as Record<string, string>,
    modes: { voice: "Stimme", text: "Text" } as Record<string, string>,
    endReasons: {
      fertig: "fertig",
      person_beendet: "von der Person beendet",
      zeitlimit: "Zeitlimit",
      technik: "Technik",
      krise: "Krise",
      minderjaehrig: "Verdacht minderjährig",
      missbrauch: "Missbrauch",
    } as Record<string, string>,
    flagged: "Hinweis",
    available: (d: string) => `vorhanden, gelöscht am ${d}`,
    gone: "gelöscht",
    open: "Transkript für diesen Sicherheitsfall öffnen",
    reason: "Begründung für den Zugriff",
    reasonHint: "Mindestens 10 Zeichen. Wird mit Zeit und Person protokolliert.",
    notice: "Der Zugriff wird protokolliert. Transkripte sind besonders schutzwürdig; nur so viel lesen, wie der Fall braucht.",
    submit: "Transkript öffnen",
    opening: "Wird geöffnet …",
    close: "Transkript schließen",
    roles: { viola: "Viola", person: "Person", system: "System" } as Record<string, string>,
    deleted: "Das Transkript ist schon gelöscht (Frist abgelaufen).",
    empty: "Das Transkript ist leer.",
    sessionInfo: "Gespräch",
    errors: {
      admin_aal2_required: "Nur mit Zwei-Faktor-Anmeldung.",
      no_safety_case: "Zu dieser Person gibt es keinen offenen Sicherheitsfall. Ohne offenen Fall ist kein Zugriff möglich.",
      reason_required: "Bitte eine Begründung mit mindestens 10 Zeichen angeben.",
      not_found: "Dieses Gespräch gibt es nicht (mehr).",
      missing_function: "Der Zugriff auf Transkripte ist in der Datenbank noch nicht freigeschaltet (Funktion api.admin_safety_transcript fehlt). Bitte nach dem Einspielen der Härtung erneut versuchen.",
    } as Record<string, string>,
  },
  errors: {
    report_not_found: "Meldung nicht gefunden oder schon abgeschlossen.",
    invalid_status: "Ungültiger Stand.",
    invalid_decision: "Bitte eine Entscheidung wählen.",
    resolution_required: "Bitte eine Begründung angeben (mindestens 3 Zeichen).",
    invalid_kind: "Bitte eine Art wählen.",
    reason_required: "Bitte eine Begründung angeben (mindestens 3 Zeichen).",
    invalid_end: "Das Ende muss in der Zukunft liegen.",
    user_not_found: "Person nicht gefunden.",
    blocklist_data_missing: "Für den Ausschluss fehlen Name und Geburtsdatum.",
    note_required: "Bitte eine Begründung angeben (mindestens 3 Zeichen).",
    appeal_not_found: "Widerspruch nicht gefunden oder schon entschieden.",
    outcome_required: "Bitte ein Ergebnis angeben.",
    sanction_not_active: "Diese Sanktion ist nicht mehr aktiv.",
  } as Record<string, string>,
};
