// Admin „Heute“: was jetzt zu tun ist, dazu Kennzahlen (nur Summen, k-anonym).

export const adminToday = {
  title: "Heute",
  lead: "Was jetzt ansteht: Freigaben, Meldungen mit 24-Stunden-Frist, Hinweise, Lokale und Abende.",
  todoTitle: "Jetzt zu tun",
  nothing: "Nichts offen.",
  runs: {
    title: "Auswahl-Läufe in Prüfung",
    empty: "Kein Lauf wartet auf Freigabe.",
    item: (pending: number) => (pending === 1 ? "1 Vorschlag offen" : `${pending} Vorschläge offen`),
    warnings: (n: number) => (n === 1 ? "1 mit Warnung" : `${n} mit Warnung`),
    period: (from: string, to: string) => `Zeitraum ${from} bis ${to}`,
    failed: (n: number) => (n === 1 ? "1 Lauf ist in den letzten 14 Tagen fehlgeschlagen." : `${n} Läufe sind in den letzten 14 Tagen fehlgeschlagen.`),
    running: "Ein Lauf ist angesetzt oder läuft gerade.",
    open: "Prüfen",
  },
  reports: {
    title: "Meldungen",
    lead: "Ziel: jede Meldung innerhalb von 24 Stunden prüfen.",
    open: "offen",
    overdue: "überfällig",
    empty: "Keine offenen Meldungen.",
    all: "Alle Meldungen",
  },
  flags: {
    title: "Sicherheits-Hinweise",
    empty: "Keine offenen Hinweise.",
    all: "Zu den Hinweisen",
  },
  reservations: {
    title: "Lokal hat noch nicht bestätigt",
    empty: "Alle Reservierungen sind bestätigt.",
    phone: "per Telefon",
    notified: (d: string) => `Mail an das Lokal ${d}`,
    notNotified: "Reservierung noch nicht verschickt",
    code: (c: string) => `Tisch ${c}`,
  },
  evenings: {
    title: "Abende ohne Ergebnis",
    text: (n: number) => (n === 1 ? "1 Abend braucht eine Entscheidung." : `${n} Abende brauchen eine Entscheidung.`),
    empty: "Kein Abend wartet auf eine Entscheidung.",
    open: "Klären",
  },
  appeals: {
    title: "Widersprüche",
    text: (n: number) => (n === 1 ? "1 Widerspruch ist offen." : `${n} Widersprüche sind offen.`),
    since: (d: string) => `ältester seit ${d}`,
    empty: "Keine offenen Widersprüche.",
    open: "Entscheiden",
  },
  provisional: (n: number) => (n === 1 ? "1 vorläufige Sperre wartet auf eine Entscheidung." : `${n} vorläufige Sperren warten auf eine Entscheidung.`),
  nextPeriod: (from: string, to: string, until: string) => `Nächster Zeitraum ${from} bis ${to}, Zeiten eintragen bis ${until}.`,
  kpi: {
    title: "Kennzahlen",
    lead: "Nur Summen. Jeder Abruf steht im Audit-Protokoll.",
    waitlist: "Warteliste (bestätigt)",
    waitlistByRegion: "Nach Region",
    waitlistBySource: "Nach Quelle (Plakat-Kürzel)",
    unconfirmed: "unbestätigt",
    invitedToApp: "in die App eingeladen",
    funnel: "Einrichtung der Konten",
    funnelLead: "Wie viele Konten jede Stufe erreicht haben.",
    stages: {
      konten: "Konto angelegt (eingeladen)",
      angemeldet: "Einladung angenommen",
      einwilligungen: "Pflicht-Einwilligungen erteilt",
      angaben: "Angaben ausgefüllt",
      identitaet: "Geschützte Angaben gemacht",
      ausweis: "Ausweis geprüft",
      gespraech: "Erstgespräch abgeschlossen",
      zusammenfassung: "Zusammenfassung bestätigt",
      bereit: "Bereit für die Auswahl",
      vorschlag: "Vorschlag erhalten",
      abend: "Erster Abend stattgefunden",
    } as Record<string, string>,
    run: "Letzter Auswahl-Lauf",
    noRun: "Noch kein Lauf.",
    pool: "im Pool",
    withProposal: "mit Vorschlag",
    share: "Anteil mit Vorschlag",
    runtime: "Laufzeit",
    evenings: "Abende",
    evTotal: "Vorschläge an Mitglieder",
    evConfirmed: "mit vereinbartem Termin",
    states: {
      proposed: "vorgeschlagen",
      time_requested: "Wunschzeit gesendet",
      time_countered: "Alternative gesendet",
      confirmed: "bestätigt",
      happened: "stattgefunden",
      cancelled_early: "früh abgesagt",
      cancelled_late: "kurzfristig abgesagt",
      no_show: "nicht erschienen",
      lapsed: "Frist verstrichen",
      declined: "abgelehnt",
    } as Record<string, string>,
    feedback: "Rückmeldungen",
    fbCount: "Rückmeldungen",
    fbMatch: "Passung (1–5)",
    fbVenue: "Lokal (1–5)",
    fbAgain: "Wieder treffen",
    fbAgainValues: { ja: "ja", vielleicht: "vielleicht", nein: "nein" } as Record<string, string>,
    fbUnsafe: "nicht sicher gefühlt",
    fbContact: "Kontakt getauscht (Abende)",
    costs: "Kosten",
    costSessions: "Gespräche mit Kostenprotokoll",
    costPerSession: "je Gespräch (Median)",
    costPerHour: "je Gesprächsstunde",
    costTarget: (t: string) => `Ziel ${t}`,
    costPerRun: "je Auswahl-Lauf (Mittel)",
    costPerProposal: "je Vorschlag",
    latency: "Antwortzeit 90 %-Wert (Median)",
    safety: "Meldungen im 24-Stunden-Ziel",
    safetyDecided: "entschieden",
    safetyInTime: "davon in der Frist",
    safetyMedian: "Median bis zur Entscheidung",
    membership: "Mitgliedschaften",
    membershipStatus: {
      free: "Gratisphase",
      pending: "bestellt",
      active: "aktiv",
      cancelled: "gekündigt",
      ended: "beendet",
      past_due: "Zahlung offen",
      withdrawn: "widerrufen",
    } as Record<string, string>,
    tiers: { auftakt: "Auftakt", andante: "Andante", loge: "Loge" } as Record<string, string>,
    stock: "Bestand",
    stockLead: "Konten, Einladungen und Ausweisprüfungen (aus der Übersicht von M2).",
    empty: "Noch keine Daten.",
  },
};
