// Admin „Warteliste“: Zahlen, weitere Einladungscodes, Einladung in die App nach Platz.

export const adminWaitlist = {
  title: "Warteliste",
  lead: "Zahlen der Warteliste und Einladung in die App in der Reihenfolge der Plätze.",
  totals: "Gesamt",
  confirmed: "bestätigt",
  unconfirmed: "unbestätigt",
  founding: "Gründungsmitglieder",
  invitedToApp: "in die App eingeladen",
  invitesCreated: "Einladungscodes erzeugt",
  invitesUsed: "davon genutzt",
  generatedAt: (d: string) => `Stand ${d}`,
  byRegion: "Nach Region",
  regionCols: { group: "Region", confirmed: "bestätigt", unconfirmed: "unbestätigt", founding: "Gründung", last: "letzte Grundnummer" },
  groups: {
    westmecklenburg: "Westmecklenburg",
    hamburg: "Hamburg",
    luebeck: "Lübeck",
    rostock: "Rostock",
    anderswo: "Anderswo",
  } as Record<string, string>,
  byDay: "Nach Tag",
  byDayLead: "Neue Einträge je Tag (Europe/Berlin), letzte 30 Tage mit Einträgen.",
  dayCols: { day: "Tag", signups: "Einträge", confirmations: "Bestätigungen" },
  chartLabel: (n: number) => `Säulendiagramm: neue Einträge an ${n} Tagen`,
  bySource: "Nach Quelle (Plakat-Kürzel)",
  sourceCols: { source: "Quelle", signups: "Einträge", confirmed: "bestätigt", hits: "Aufrufe", recent: "Aufrufe 30 Tage" },
  noSource: "(ohne)",
  empty: "Noch keine Einträge.",
  invite: {
    title: "In die App einladen",
    lead: "Bestätigte Einträge einer Region in der Reihenfolge des Platzes. Eingeladene Personen bekommen ein Konto (kostenlos, ein Gratis-Abend) und eine Mail mit dem Link zur Anmeldung.",
    region: "Region",
    count: "Wie viele",
    show: "Einträge zeigen",
    includeInvited: "Auch schon Eingeladene zeigen",
    cols: { select: "Auswahl", place: "Platz", name: "Vorname", email: "E-Mail", region: "Ort", source: "Quelle", confirmed: "Bestätigt", invited: "In App", action: "Code" },
    selectRow: (name: string, place: number) => `Platz ${place}, ${name} auswählen`,
    selectFirst: (n: number) => `Erste ${n} auswählen`,
    clear: "Auswahl aufheben",
    founding: "Gründung",
    invited: (d: string) => `eingeladen ${d}`,
    submit: (n: number) => (n === 1 ? "1 Person einladen" : `${n} Personen einladen`),
    dialogTitle: (n: number) => (n === 1 ? "1 Person in die App einladen?" : `${n} Personen in die App einladen?`),
    dialogText: "Für jede Person entsteht ein Konto, und sie bekommt sofort eine Einladungs-Mail. Die Einladung gilt 7 Tage.",
    confirm: "Einladen",
    result: (ok: number, failed: number) => (failed === 0 ? `${ok} eingeladen.` : `${ok} eingeladen, ${failed} nicht möglich.`),
    failedItem: (email: string, reason: string) => `${email}: ${reason}`,
    empty: "Keine bestätigten Einträge ohne Einladung in dieser Region.",
    none: "Nichts ausgewählt.",
  },
  grant: {
    submit: "Weiteren Code",
    label: (name: string) => `Weiteren Einladungscode für ${name}`,
    done: (code: string) => `Neuer Code: ${code}`,
  },
  errors: {
    invalid_region_group: "Unbekannte Region.",
    already_member: "Hat bereits ein Konto.",
    invalid_email: "Ungültige E-Mail-Adresse.",
    waitlist_missing: "Eintrag nicht gefunden.",
  } as Record<string, string>,
};
