// Admin-Bereich (nur mit Zwei-Faktor). Sachlich, kurz.

export const admin = {
  area: "Admin",
  navLabel: "Admin-Navigation",
  nav: {
    overview: "Übersicht",
    accounts: "Konten",
    invite: "Einladen",
    verifications: "Ausweisprüfungen",
    flags: "Sicherheits-Hinweise",
    settings: "Einstellungen",
  },
  toApp: "Zur App",
  notAdmin: "Kein Zugang",
  dashboard: {
    title: "Übersicht",
    lead: "Stand von Konten, Einladungen, Prüfungen und Hinweisen.",
    accounts: "Konten",
    byStatus: "nach Stand",
    invitations: "Einladungen",
    open: "offen",
    accepted: "angenommen",
    expired: "abgelaufen",
    verifications: "Ausweisprüfungen",
    pendingDeletion: "Didit-Sitzungen noch zu löschen",
    flags: "Offene Sicherheits-Hinweise",
    reports: "Offene Meldungen",
    waitlist: "Warteliste",
    waitlistInvited: "davon eingeladen",
    waitlistMissing: "Warteliste nicht verbunden",
    later: "Weitere Bereiche (Auswahl, Abende, Lokale, Meldungen, Mitgliedschaften) folgen mit M3–M7.",
  },
  status: {
    onboarding: "Einrichtung",
    active: "aktiv",
    paused: "pausiert",
    suspended: "gesperrt",
    closed: "geschlossen",
  } as Record<string, string>,
  steps: {
    einwilligungen: "Einwilligungen",
    angaben: "Angaben",
    identitaet: "Identität",
    ausweis: "Ausweis",
    fertig: "fertig",
  } as Record<string, string>,
  verificationStatus: {
    started: "begonnen",
    approved: "bestätigt",
    declined: "abgelehnt",
    in_review: "in Prüfung",
    expired: "abgelaufen",
    error: "Fehler",
    blocked: "gesperrt (Sperrliste)",
  } as Record<string, string>,
  accounts: {
    title: "Konten",
    lead: "Suche nach E-Mail, Name oder Postleitzahl.",
    search: "Suchen",
    searchLabel: "Suchbegriff",
    statusFilter: "Stand",
    all: "alle",
    empty: "Keine Konten gefunden.",
    cols: { person: "Person", place: "Ort", status: "Stand", step: "Schritt", verification: "Ausweis", created: "Seit" },
    founding: "Gründung",
  },
  account: {
    back: "Zurück zu den Konten",
    facts: "Angaben",
    onboarding: "Einrichtung",
    consents: "Einwilligungen (Verlauf)",
    verifications: "Ausweisprüfungen",
    invitations: "Einladungen",
    membership: "Mitgliedschaft",
    flags: "Sicherheits-Hinweise",
    noArt9: "Besonders geschützte Angaben (Geschlecht, Religion) sind hier bewusst nicht sichtbar.",
    granted: "erteilt",
    revoked: "widerrufen",
    none: "keine",
    yes: "ja",
    no: "nein",
  },
  invite: {
    title: "Einladen",
    lead: "Lädt eine Person per E-Mail ein. Fermata legt das Konto an (kostenlos, ein Gratis-Abend) und markiert den Eintrag auf der Warteliste.",
    email: "E-Mail-Adresse",
    submit: "Einladung senden",
    sending: "Wird gesendet …",
    success: (email: string) => `Einladung an ${email} ist unterwegs.`,
    mailFailed: "Das Konto ist angelegt, die Mail kam aber nicht an. Bitte erneut einladen.",
    founding: "Gründungsmitglied laut Warteliste.",
    errors: {
      invalid_email: "Bitte eine gültige E-Mail-Adresse eingeben.",
      already_member: "Diese Person hat bereits ein Konto.",
      admin_aal2_required: "Nur mit Zwei-Faktor-Anmeldung.",
    } as Record<string, string>,
    listTitle: "Letzte Einladungen",
    states: { offen: "offen", angenommen: "angenommen", abgelaufen: "abgelaufen", ersetzt: "ersetzt" } as Record<string, string>,
    cols: { email: "E-Mail", state: "Stand", invited: "Eingeladen", until: "Gültig bis", waitlist: "Warteliste" },
  },
  verifications: {
    title: "Ausweisprüfungen",
    lead: "Gespeichert sind nur: volljährig, Geburtsjahr, Abgleich von Name und Geburtsdatum, Sperrliste und ob die Sitzung bei Didit gelöscht ist.",
    empty: "Noch keine Prüfungen.",
    cols: { person: "Person", status: "Ergebnis", adult: "18+", year: "Jahrgang", name: "Name", birth: "Geburtsdatum", blocklist: "Sperrliste", deleted: "Bei Didit gelöscht", started: "Begonnen" },
  },
  flags: {
    title: "Sicherheits-Hinweise",
    lead: "Namens-Treffer der Sperrliste, automatische Sperren und Hinweise des Systems. Bearbeiten folgt mit M7.",
    empty: "Keine offenen Hinweise.",
    showAll: "Auch erledigte zeigen",
    showOpen: "Nur offene zeigen",
    cols: { severity: "Dringlichkeit", kind: "Art", person: "Person", source: "Quelle", created: "Seit", reviewed: "Erledigt" },
    kinds: {
      sperrliste_ausweis: "Ausweis auf der Sperrliste (gesperrt)",
      sperrliste_name: "Name auf der Sperrliste (Verdacht)",
      minderjaehrig: "Laut Ausweis minderjährig",
      konto_geloescht_waehrend_pruefung: "Konto während einer Prüfung gelöscht",
    } as Record<string, string>,
  },
  settings: {
    title: "Einstellungen",
    lead: "Alle Startwerte als Einstellung. Jede Änderung steht mit Zeit und Person im Verlauf.",
    value: "Wert (JSON)",
    save: "Speichern",
    saved: "Gespeichert.",
    public: "öffentlich",
    placeholder: "Platzhalter",
    errors: {
      invalid_json: "Das ist kein gültiges JSON.",
      type_mismatch: "Der Typ muss gleich bleiben (zum Beispiel Zahl bleibt Zahl).",
      unknown_setting: "Unbekannte Einstellung.",
      invalid_value: "Ungültiger Wert.",
    } as Record<string, string>,
    updated: (date: string) => `Geändert ${date}`,
  },
};
