// Admin „Auswahl“: Läufe, Vorschläge prüfen, freigeben, ablehnen, Lauf abschließen, Bericht.

export const adminRuns = {
  title: "Auswahl",
  lead: "Kein Vorschlag geht ohne Freigabe raus. Personen erscheinen nur mit Anzeigename und Altersband.",
  listTitle: "Läufe",
  empty: "Noch kein Auswahl-Lauf.",
  cols: {
    period: "Zeitraum",
    status: "Stand",
    started: "Gestartet",
    pool: "Pool",
    pairs: "Vorschläge",
    pending: "offen",
    approved: "freigegeben",
    rejected: "abgelehnt",
    cost: "Kosten",
  },
  status: {
    scheduled: "angesetzt",
    running: "läuft",
    review: "in Prüfung",
    approved: "freigegeben",
    partially_approved: "teilweise freigegeben",
    failed: "fehlgeschlagen",
    cancelled: "alles abgelehnt",
  } as Record<string, string>,
  open: "Öffnen",
  detail: {
    back: "Alle Läufe",
    title: (from: string, to: string) => `Lauf für ${from} bis ${to}`,
    titleNoPeriod: "Auswahl-Lauf",
    summary: "Überblick",
    error: "Fehler des Laufs",
    pool: "im Pool",
    pairs: "Vorschläge",
    pending: "offen",
    approved: "freigegeben",
    rejected: "abgelehnt",
    cost: "Kosten",
    runtime: "Laufzeit",
    finishedAt: "Fertig",
    notReview: "Dieser Lauf ist nicht in Prüfung. Entscheidungen sind nicht mehr möglich.",
  },
  pairings: {
    title: "Vorschläge",
    lead: "Tastatur: Pfeil hoch/runter oder j/k springt zum vorigen oder nächsten Vorschlag.",
    empty: "Dieser Lauf hat keine Vorschläge.",
    filterAll: "Alle",
    filterPending: "Offen",
    filterWarnings: "Mit Warnung",
    filterLabel: "Vorschläge zeigen",
    count: (shown: number, total: number) => `${shown} von ${total}`,
    and: "und",
    ageBand: (b: string | null) => (b ? `${b} Jahre` : "Alter unbekannt"),
    total: "Gesamt",
    rule: "Regeln",
    llm: "Sprachmodell",
    bonus: "Wartebonus",
    noLlm: "keine Bewertung",
    subscores: "Teil-Scores",
    sub: {
      werte: "Werte",
      wuensche: "Wünsche",
      lebensumstaende: "Lebensumstände",
      persoenlichkeit: "Persönlichkeit",
      zeiten: "Zeiten",
    } as Record<string, string>,
    rationale: "Begründung des Sprachmodells",
    noRationale: "Keine Begründung (nur Regeln).",
    review: "Prüf-Agent",
    recommendation: "Empfehlung",
    recommendations: { freigeben: "freigeben", genauer_pruefen: "genauer prüfen", ablehnen: "ablehnen" } as Record<string, string>,
    assessment: "Einschätzung",
    risks: "Risiken",
    hints: "Hinweise",
    agentError: "Prüf-Agent nicht erreichbar",
    art9Ok: "Wortfilter ohne Treffer",
    art9Hits: (cats: string) => `Wortfilter: Treffer (${cats})`,
    art9Suspicion: "Prüf-Agent: Verdacht auf besonders geschützte Inhalte",
    replaced: "„Warum Sie beide“ wurde durch den neutralen Ersatztext ersetzt.",
    warning: "Warnung",
    reasons: "„Warum Sie beide“ (sehen beide)",
    noReasons: "Kein Text.",
    venue: "Lokal",
    noVenue: "Kein Lokal",
    times: "Terminvorschläge",
    timesPreview: "Vorschau, wird bei der Freigabe neu berechnet",
    noTimes: "Keine freien Termine im Lokal. Eine Freigabe ist so nicht möglich.",
    decided: (d: string) => `Entschieden ${d}`,
    comment: "Kommentar",
    commentHint: "Für das Protokoll. Beim Ablehnen Pflicht.",
    approve: "Freigeben",
    approving: "Wird freigegeben …",
    reject: "Ablehnen",
    rejecting: "Wird abgelehnt …",
    approvedMsg: "Freigegeben. Der Vorschlag ist unterwegs.",
    rejectedMsg: "Abgelehnt.",
    rejectNeedsComment: "Bitte beim Ablehnen kurz begründen (mindestens 3 Zeichen).",
    select: "Für Sammelfreigabe auswählen",
    selectDisabled: "Nur Vorschläge ohne Warnung lassen sich gesammelt freigeben.",
    statusLabel: {
      pending_review: "offen",
      approved: "freigegeben",
      proposed: "vorgeschlagen",
      rejected: "abgelehnt",
      declined: "abgelehnt (Mitglied)",
      expired: "verfallen",
      completed: "abgeschlossen",
      cancelled: "abgesagt",
    } as Record<string, string>,
    evening: "Abend angelegt",
  },
  bulk: {
    title: "Sammelfreigabe",
    lead: "Nur für Vorschläge ohne Warnung.",
    selectAll: (n: number) => `Alle ohne Warnung auswählen (${n})`,
    clear: "Auswahl aufheben",
    submit: (n: number) => (n === 1 ? "1 Vorschlag freigeben" : `${n} Vorschläge freigeben`),
    dialogTitle: (n: number) => (n === 1 ? "1 Vorschlag freigeben?" : `${n} Vorschläge freigeben?`),
    dialogText: "Für jeden Vorschlag entsteht ein Abend mit Terminvorschlägen, und beide Personen bekommen eine Nachricht.",
    confirm: "Jetzt freigeben",
    result: (ok: number, failed: number) =>
      failed === 0 ? `${ok} freigegeben.` : `${ok} freigegeben, ${failed} nicht möglich.`,
    none: "Nichts ausgewählt.",
  },
  finish: {
    title: "Lauf abschließen",
    lead: "Danach sind keine Entscheidungen mehr möglich. Der Bericht bekommt die Zahlen der Freigabe.",
    pending: (n: number) => (n === 1 ? "1 Vorschlag ist noch offen." : `${n} Vorschläge sind noch offen.`),
    rejectPending: "Offene Vorschläge beim Abschluss ablehnen",
    submit: "Lauf abschließen",
    dialogTitle: "Lauf abschließen?",
    dialogText: "Der Lauf wird abgeschlossen. Offene Vorschläge werden abgelehnt, wenn das Häkchen gesetzt ist.",
    confirm: "Abschließen",
    done: (status: string) => `Lauf abgeschlossen: ${status}.`,
    needReject: "Es sind noch Vorschläge offen. Bitte entscheiden oder das Häkchen setzen.",
  },
  report: {
    title: "Bericht",
    pool: "Pool",
    poolLead: "Wer nicht im Pool war (erster Grund je Person).",
    accounts: "Konten",
    inPool: "im Pool",
    filter: "Harte Filter",
    filterLead: "Verworfene Paare je Filter (erster Grund je Paar).",
    checked: "Paare geprüft",
    passed: "bestanden",
    preselect: "nach Vorauswahl",
    minScore: (v: string) => `über dem Mindestscore ${v}`,
    scores: "Verteilung der Scores",
    scoresLead: "Qualität aus Regeln und Sprachmodell (0 bis 1), ohne Wartebonus.",
    scoreKinds: {
      regel: "Regeln",
      llm: "Sprachmodell",
      qualitaet: "Qualität",
      gesamt_mit_bonus: "Gesamt mit Bonus",
      vorgeschlagen: "Vorgeschlagene",
    } as Record<string, string>,
    dist: { n: "Anzahl", min: "Min.", median: "Median", mean: "Mittel", max: "Max." },
    histogram: "Qualität der bewerteten Paare",
    histogramLabel: (n: number) => `Histogramm der Qualität, ${n} Paare, in Zehntel-Schritten von 0 bis 1`,
    bucket: (from: string, to: string) => `${from}–${to}`,
    result: "Ergebnis",
    proposals: "Vorschläge",
    share: "Anteil des Pools mit Vorschlag",
    withoutReason: "Ohne Vorschlag je Grund",
    unmatched: {
      keine_kandidaten: "keine Kandidaten",
      unter_mindestscore: "unter dem Mindestscore",
      nicht_zugeordnet: "nicht zugeordnet",
      kein_lokal: "kein Lokal frei",
    } as Record<string, string>,
    fairness: "Fairness",
    fairnessLead: (k: number) => `Nur Zählungen, getrennt nach Geschlecht und nach Altersband, nie gekreuzt. Gruppen unter ${k} Personen sind ausgeblendet.`,
    byGender: "Nach Geschlecht",
    byAge: "Nach Altersband",
    group: "Gruppe",
    inPoolCol: "im Pool",
    proposedCol: "mit Vorschlag",
    shareCol: "Anteil",
    hidden: (n: number, sum: number | null) =>
      sum === null ? `${n} kleine Gruppen ausgeblendet.` : `${n} kleine Gruppen zusammengefasst: ${sum} im Pool.`,
    tooFew: "zu wenige für einen Anteil",
    genders: { frau: "Frauen", mann: "Männer", nichtbinaer: "nichtbinär", unbekannt: "unbekannt" } as Record<string, string>,
    venues: "Lokale",
    perVenue: "Vorschläge je Lokal",
    ratioExceeded: "Anfahrtsverhältnis überschritten",
    review: "Prüfung",
    replaced: "Ersatztext verwendet",
    filterHits: "Treffer des Wortfilters",
    agentSuspicion: "Verdacht des Prüf-Agenten",
    recommendations: "Empfehlungen",
    llm: "Sprachmodell und Kosten",
    llmModel: "Modell",
    llmCalls: "Bewertungen angefragt",
    llmReused: "wiederverwendet",
    llmErrors: "Fehler",
    llmRefusals: "Ablehnungen",
    llmReviewCalls: "Aufrufe Prüf-Agent",
    tokens: "Token (Eingabe / Ausgabe / Cache lesen / Cache schreiben)",
    costLlm: "Sprachmodell",
    costEmb: "Embeddings",
    costTotal: "Gesamt",
    costNote: "Schätzung aus Token und Listenpreisen (Einstellungen matching.*price*).",
    runtime: "Laufzeit je Stufe",
    stage: "Stufe",
    seconds: "Sekunden",
    stages: {
      pool: "Pool",
      embeddings: "Embeddings",
      filter: "Filter",
      art9_pruefung: "Prüffunktionen (Ja/Nein)",
      regel_scores: "Regel-Scores",
      vorauswahl: "Vorauswahl",
      llm: "Sprachmodell",
      speichern_kandidaten: "Kandidaten speichern",
      zuordnung_und_lokal: "Zuordnung und Lokal",
      pruef_agent: "Prüf-Agent",
      speichern: "Speichern",
      bericht: "Bericht",
      gesamt: "Gesamt",
    } as Record<string, string>,
    reason: "Grund",
    count: "Anzahl",
    empty: "Der Bericht ist leer.",
    poolReasons: {
      nicht_aktiv: "Konto nicht aktiv",
      loeschung_beantragt: "Löschung beantragt",
      nicht_verifiziert: "Ausweis nicht geprüft",
      einwilligung_gespraech: "Einwilligung Gespräch fehlt",
      einwilligung_art9: "Einwilligung geschützte Angaben fehlt",
      kein_profil: "kein Profil",
      zusammenfassung_unbestaetigt: "Zusammenfassung nicht bestätigt",
      nicht_bereit: "nicht bereit",
      kein_geburtsjahr: "Geburtsjahr fehlt",
      gesperrt: "gesperrt",
      keine_plz: "keine Postleitzahl",
      keine_zeiten: "keine freien Zeiten",
      kein_abend_frei: "kein Abend frei",
      offener_abend: "laufender Abend",
      offener_vorschlag: "offener Vorschlag",
    } as Record<string, string>,
    filterReasons: {
      entfernung: "Entfernung",
      alter: "Alter",
      sprache: "Sprache",
      dealbreaker_raucht: "Ausschluss: raucht",
      dealbreaker_hat_kinder: "Ausschluss: hat Kinder",
      dealbreaker_will_kinder: "Ausschluss: will Kinder",
      dealbreaker_will_keine_kinder: "Ausschluss: will keine Kinder",
      dealbreaker_alter: "Ausschluss: Alter",
      dealbreaker_entfernung: "Ausschluss: Entfernung",
      schon_vorgeschlagen: "schon vorgeschlagen",
      blockiert: "blockiert",
      kuerzlich_abgelehnt: "kürzlich abgelehnt",
      keine_gemeinsame_zeit: "keine gemeinsame Zeit",
      kein_lokal: "kein Lokal",
      geschlecht: "Geschlecht (Prüffunktion)",
      religion: "Religion (Prüffunktion)",
    } as Record<string, string>,
  },
  errors: {
    no_data_found: "Nicht gefunden.",
    comment_required: "Bitte beim Ablehnen kurz begründen (mindestens 3 Zeichen).",
  } as Record<string, string>,
};
