// Gemeinsame Texte des Admin-Bereichs (UI-Welle). Sachlich, kurz, ohne Anrede.

export const adminCommon = {
  kLess: (k: number) => `< ${k}`,
  kLessLong: (k: number) => `weniger als ${k} – aus Datenschutzgründen nicht gezeigt`,
  kNote: (k: number) => `Zahlen unter ${k} stehen als „< ${k}“ (k-Anonymität, docs/KENNZAHLEN.md).`,
  none: "–",
  yes: "ja",
  no: "nein",
  open: "offen",
  all: "alle",
  show: "Anzeigen",
  filter: "Filtern",
  details: "Einzelheiten",
  back: "Zurück",
  cancel: "Abbrechen",
  confirm: "Bestätigen",
  save: "Speichern",
  saving: "Wird gespeichert …",
  saved: "Gespeichert.",
  working: "Wird ausgeführt …",
  copy: "Kopieren",
  copied: "Kopiert.",
  copyFailed: "Kopieren nicht möglich. Bitte den Text markieren und kopieren.",
  person: "Person",
  persons: "Personen",
  toAccount: "Konto ansehen",
  loggedNotice: "Jeder Zugriff steht im Audit-Protokoll.",
  subnav: "Bereich",
  chartTable: "Werte als Tabelle",
  chartFrom: "von",
  chartTo: "bis",
  chartCount: "Anzahl",
  chartValue: "Wert",
  overdueSince: (d: string) => `überfällig seit ${d}`,
  dueIn: (d: string) => `fällig in ${d}`,
  dueAt: (d: string) => `Frist ${d}`,
  hours: (n: number) => (n === 1 ? "1 Std." : `${n} Std.`),
  minutes: (n: number) => (n === 1 ? "1 Min." : `${n} Min.`),
  days: (n: number) => (n === 1 ? "1 Tag" : `${n} Tagen`),
  severity: { akut: "akut", hoch: "hoch", mittel: "mittel", niedrig: "niedrig" } as Record<string, string>,
  severityLabel: "Dringlichkeit",
  errors: {
    generic: "Das hat nicht geklappt. Bitte gleich noch einmal versuchen.",
    admin_aal2_required: "Nur mit Zwei-Faktor-Anmeldung. Bitte neu anmelden.",
    admin_required: "Nur mit Zwei-Faktor-Anmeldung. Bitte neu anmelden.",
    network: "Keine Verbindung zum Server.",
    missing_function: "Diese Funktion gibt es in der Datenbank noch nicht.",
    invalid_input: "Bitte die Eingaben prüfen.",
    not_found: "Nicht gefunden.",
  } as Record<string, string>,
};
