// Gespräch mit Viola (M3): Start, Stimme, Text, Zusammenfassung, Verlauf. Sie/Du über af().
import { af, type AddressForm } from "./form";

export const gespraech = (f: AddressForm) => ({
  title: "Gespräch",
  eyebrow: "Viola",
  lead: af(
    f,
    "Viola lernt Sie in einem ruhigen Gespräch kennen. Danach lesen Sie die Zusammenfassung und bestätigen sie selbst.",
    "Viola lernt dich in einem ruhigen Gespräch kennen. Danach liest du die Zusammenfassung und bestätigst sie selbst.",
  ),
  aboutTitle: "Wer ist Viola?",
  about: [
    af(f, "Viola ist eine künstliche Intelligenz, kein Mensch. Sie hat kein Gesicht, nur eine Stimme.", "Viola ist eine künstliche Intelligenz, kein Mensch. Sie hat kein Gesicht, nur eine Stimme."),
    af(f, "Sie fragt nach Ihrer Persönlichkeit, Ihren Werten, Wünschen an ein Gegenüber, Ihren Lebensumständen, wie weit Sie fahren und wann Sie Zeit haben.", "Sie fragt nach deiner Persönlichkeit, deinen Werten, Wünschen an ein Gegenüber, deinen Lebensumständen, wie weit du fährst und wann du Zeit hast."),
    af(f, "Nach Gesundheit, Religion, Politik, Herkunft oder Sexualität fragt Viola nie. Erzählen Sie davon, speichert Fermata es nicht.", "Nach Gesundheit, Religion, Politik, Herkunft oder Sexualität fragt Viola nie. Erzählst du davon, speichert Fermata es nicht."),
  ],
  factsTitle: "Was mit dem Gespräch passiert",
  facts: [
    af(f, "Ihre Stimme wird nicht aufgezeichnet, nirgends.", "Deine Stimme wird nicht aufgezeichnet, nirgends."),
    "Der Gesprächstext wird nach 30 Tagen gelöscht.",
    af(f, "Die Zusammenfassung lesen Sie selbst und bestätigen oder korrigieren sie.", "Die Zusammenfassung liest du selbst und bestätigst oder korrigierst sie."),
    af(f, "Sie können jederzeit aufhören oder zum Schreiben wechseln.", "Du kannst jederzeit aufhören oder zum Schreiben wechseln."),
  ],
  addressNote: af(f, "Viola spricht Sie mit „Sie“ an. Das können Sie im Konto ändern.", "Viola spricht dich mit „Du“ an. Das kannst du im Konto ändern."),
  addressLink: "Anrede ändern",
  aiNoteLink: "Hinweis zu künstlicher Intelligenz",
  atemLabel: "Viola ist bereit.",

  kindTitle: "Welches Gespräch?",
  kinds: {
    erstgespraech: { title: "Erstes Gespräch", text: af(f, "Etwa 20 bis 45 Minuten, je nach Stufe. Sie können es in Teilen führen.", "Etwa 20 bis 45 Minuten, je nach Stufe. Du kannst es in Teilen führen.") },
    vertiefung: { title: "Vertiefung", text: af(f, "Viola knüpft an Ihre Zusammenfassung an und fragt genauer nach.", "Viola knüpft an deine Zusammenfassung an und fragt genauer nach.") },
    korrektur: { title: "Zusammenfassung korrigieren", text: af(f, "Kurz besprechen, was in Ihrer Zusammenfassung nicht stimmt.", "Kurz besprechen, was in deiner Zusammenfassung nicht stimmt.") },
    nachbesprechung: { title: "Nachbesprechung", text: af(f, "Wie war der Abend, und was soll beim nächsten Vorschlag anders sein? Über Ihr Gegenüber spricht Viola nicht.", "Wie war der Abend, und was soll beim nächsten Vorschlag anders sein? Über dein Gegenüber spricht Viola nicht.") },
  } as Record<string, { title: string; text: string }>,
  kindNames: { erstgespraech: "Erstes Gespräch", vertiefung: "Vertiefung", korrektur: "Korrektur", nachbesprechung: "Nachbesprechung" } as Record<string, string>,
  debriefLead: (when: string, minutes: number) =>
    af(f, `Nachbesprechung zum Abend ${when}, etwa ${minutes} Minuten.`, `Nachbesprechung zum Abend ${when}, etwa ${minutes} Minuten.`),

  chooseTitle: af(f, "Wie möchten Sie sprechen?", "Wie möchtest du sprechen?"),
  speak: "Sprechen",
  speakText: af(f, "Mit Mikrofon. Ihr Browser fragt gleich, ob Fermata es benutzen darf.", "Mit Mikrofon. Dein Browser fragt gleich, ob Fermata es benutzen darf."),
  write: "Lieber schreiben",
  writeText: af(f, "Dasselbe Gespräch als Text, in Ihrem Tempo.", "Dasselbe Gespräch als Text, in deinem Tempo."),
  voiceOff: af(f, "Sprechen ist gerade nicht möglich. Schreiben geht.", "Sprechen ist gerade nicht möglich. Schreiben geht."),

  consentTitle: "Einwilligung zum Gespräch",
  consentLead: af(
    f,
    "Für das Gespräch brauchen wir Ihre Einwilligung: Fermata verarbeitet, was Sie Viola erzählen, um passende Abende vorzuschlagen.",
    "Für das Gespräch brauchen wir deine Einwilligung: Fermata verarbeitet, was du Viola erzählst, um passende Abende vorzuschlagen.",
  ),
  consentAgree: af(f, "Ich habe den Text gelesen und willige ein.", "Ich habe den Text gelesen und willige ein."),
  consentSubmit: "Einwilligen und weiter",
  consentRead: "Ganzen Text lesen",

  notVerifiedTitle: "Erst den Ausweis prüfen",
  notVerifiedText: af(f, "Das Gespräch ist möglich, sobald Ihr Konto eingerichtet ist.", "Das Gespräch ist möglich, sobald dein Konto eingerichtet ist."),
  notVerifiedCta: "Zum nächsten Schritt",

  openTitle: "Ein Gespräch ist noch offen",
  openText: af(f, "Sie können es als Text fortsetzen. Viola kennt den bisherigen Verlauf.", "Du kannst es als Text fortsetzen. Viola kennt den bisherigen Verlauf."),
  openCta: "Als Text weitermachen",
  continueTitle: "Fortsetzen",
  continueText: af(f, "Ihr letztes Gespräch endete vor dem Abschluss. Sie können dort weitermachen, wo es aufgehört hat.", "Dein letztes Gespräch endete vor dem Abschluss. Du kannst dort weitermachen, wo es aufgehört hat."),
  continueSpeak: "Weiter sprechen",
  continueWrite: "Weiter schreiben",

  // Mikrofon
  micTitle: "Mikrofon",
  micChecking: "Mikrofon wird geprüft …",
  micProblems: {
    denied: af(f, "Der Browser hat das Mikrofon nicht freigegeben. Erlauben Sie es in den Einstellungen der Seite (meist über das Schloss neben der Adresse) und versuchen Sie es noch einmal. Oder schreiben Sie lieber.", "Der Browser hat das Mikrofon nicht freigegeben. Erlaube es in den Einstellungen der Seite (meist über das Schloss neben der Adresse) und versuch es noch einmal. Oder schreib lieber."),
    no_device: af(f, "Wir finden kein Mikrofon. Schließen Sie eines an oder schreiben Sie lieber.", "Wir finden kein Mikrofon. Schließ eines an oder schreib lieber."),
    busy: af(f, "Das Mikrofon wird gerade von einem anderen Programm benutzt. Schließen Sie es dort und versuchen Sie es noch einmal.", "Das Mikrofon wird gerade von einem anderen Programm benutzt. Schließ es dort und versuch es noch einmal."),
    insecure: "Das Mikrofon geht nur über eine sichere Verbindung (https).",
    unsupported: af(f, "Dieser Browser unterstützt das Gespräch mit Stimme nicht. Schreiben Sie lieber oder nutzen Sie einen aktuellen Browser.", "Dieser Browser unterstützt das Gespräch mit Stimme nicht. Schreib lieber oder nutze einen aktuellen Browser."),
    unknown: af(f, "Das Mikrofon ließ sich nicht starten. Versuchen Sie es noch einmal oder schreiben Sie lieber.", "Das Mikrofon ließ sich nicht starten. Versuch es noch einmal oder schreib lieber."),
  } as Record<string, string>,
  micRetry: "Noch einmal versuchen",

  // KI-Hinweis (Art. 50 AI Act)
  aiNoticeTitle: "Hinweis: Viola ist eine künstliche Intelligenz",

  // Stimme
  connecting: "Verbindung wird aufgebaut …",
  waitingForViola: "Viola kommt gleich dazu …",
  states: { ruhig: "Viola ist bereit.", hoert: "Viola hört zu.", denkt: "Viola überlegt.", spricht: "Viola spricht.", pause: "Gespräch pausiert." } as Record<string, string>,
  pause: "Pause",
  resume: "Weiter",
  pausedNote: af(f, "Ihr Mikrofon ist stumm. Viola hört nichts, bis Sie weitermachen.", "Dein Mikrofon ist stumm. Viola hört nichts, bis du weitermachst."),
  switchToText: "Text statt Stimme",
  end: "Beenden",
  endTitle: "Gespräch beenden?",
  endText: af(f, "Was Sie bisher erzählt haben, bleibt gespeichert. Sie können später weitermachen.", "Was du bisher erzählt hast, bleibt gespeichert. Du kannst später weitermachen."),
  endConfirm: "Ja, beenden",
  endCancel: "Weiter sprechen",
  endCancelText: "Weiter schreiben",
  audioBlocked: af(f, "Ihr Browser hat den Ton angehalten.", "Dein Browser hat den Ton angehalten."),
  audioStart: "Ton einschalten",
  captionsLabel: "Untertitel",
  captionsShow: "Untertitel zeigen",
  captionsHide: "Untertitel ausblenden",
  captionsNote: "Untertitel werden nicht gespeichert.",
  speakerViola: "Viola",
  speakerMe: af(f, "Sie", "Du"),
  lostTitle: "Die Verbindung ist abgebrochen",
  lostText: af(f, "Was Sie bisher erzählt haben, ist gespeichert. Sie können als Text weitermachen oder neu verbinden.", "Was du bisher erzählt hast, ist gespeichert. Du kannst als Text weitermachen oder neu verbinden."),
  reconnect: "Neu verbinden",
  switchingNote: af(f, "Sie schreiben jetzt weiter. Viola kennt den bisherigen Verlauf.", "Du schreibst jetzt weiter. Viola kennt den bisherigen Verlauf."),
  violaSwitched: "Viola hat zum Schreiben gewechselt.",

  // Text
  chatLabel: "Gespräch mit Viola",
  inputLabel: af(f, "Ihre Nachricht", "Deine Nachricht"),
  inputHint: "Höchstens 2000 Zeichen. Enter schickt ab, Umschalt und Enter macht eine neue Zeile.",
  send: "Senden",
  sending: "Viola schreibt …",
  remaining: (min: number) => (min === 1 ? "noch etwa 1 Minute" : `noch etwa ${min} Minuten`),
  tooLong: "Die Nachricht ist zu lang (höchstens 2000 Zeichen).",
  summaryProposedTitle: "Violas Zusammenfassung",
  summaryProposedHint: af(f, "Antworten Sie Viola, ob das so stimmt. Danach lesen Sie die Zusammenfassung noch einmal in Ruhe.", "Antworte Viola, ob das so stimmt. Danach liest du die Zusammenfassung noch einmal in Ruhe."),
  summaryPartialHint: "Das ist ein Zwischenstand. Beim nächsten Mal geht es hier weiter.",
  summaryProposedHintVoice: af(f, "Sagen Sie Viola, ob das so stimmt. Danach lesen Sie die Zusammenfassung noch einmal in Ruhe.", "Sag Viola, ob das so stimmt. Danach liest du die Zusammenfassung noch einmal in Ruhe."),

  // Krise
  crisisTitle: "Hilfe in schweren Momenten",
  crisisText: "Die Telefonseelsorge ist rund um die Uhr da, kostenlos und anonym.",
  crisisLineName: "Telefonseelsorge",
  crisisEmergency: (n: string) => `Notruf ${n}`,
  crisisCall: (n: string) => `${n} anrufen`,

  // Ende
  endedTitle: "Danke für das Gespräch",
  endedText: af(f, "Viola schreibt jetzt die Zusammenfassung. Das dauert meist weniger als eine Minute.", "Viola schreibt jetzt die Zusammenfassung. Das dauert meist weniger als eine Minute."),
  endedNoSummary: af(f, "Das Gespräch ist beendet. Wenn Sie möchten, können Sie später weitermachen.", "Das Gespräch ist beendet. Wenn du möchtest, kannst du später weitermachen."),
  endedSafety: af(f, "Das Gespräch ist beendet. Wenn Sie Hilfe brauchen, finden Sie sie hier jederzeit.", "Das Gespräch ist beendet. Wenn du Hilfe brauchst, findest du sie hier jederzeit."),
  toSummary: "Zur Zusammenfassung",
  backToStart: "Zurück zum Gespräch",
  toHelp: "Hilfe und Sicherheit",

  // Fehler aus interview-token und dem Textdienst
  errors: {
    consent_missing: af(f, "Für das Gespräch fehlt noch Ihre Einwilligung.", "Für das Gespräch fehlt noch deine Einwilligung."),
    not_verified: af(f, "Das Gespräch ist erst nach der Ausweisprüfung möglich.", "Das Gespräch ist erst nach der Ausweisprüfung möglich."),
    suspended: af(f, "Ihr Konto ist gerade gesperrt. Wir melden uns per E-Mail.", "Dein Konto ist gerade gesperrt. Wir melden uns per E-Mail."),
    account_inactive: af(f, "Ihr Konto ist gerade nicht aktiv.", "Dein Konto ist gerade nicht aktiv."),
    kind_not_allowed: af(f, "Dieses Gespräch ist in Ihrer Stufe nicht enthalten.", "Dieses Gespräch ist in deiner Stufe nicht enthalten."),
    evening_not_eligible: "Für diesen Abend ist keine Nachbesprechung möglich.",
    no_profile_yet: af(f, "Dafür braucht es zuerst eine bestätigte Zusammenfassung.", "Dafür braucht es zuerst eine bestätigte Zusammenfassung."),
    invalid_continuation: "Dieses Gespräch lässt sich nicht mehr fortsetzen. Ein neues geht jederzeit.",
    session_active: af(f, "Es läuft schon ein Gespräch. Sie können es als Text fortsetzen.", "Es läuft schon ein Gespräch. Du kannst es als Text fortsetzen."),
    session_closed: "Dieses Gespräch ist schon beendet.",
    daily_limit: af(f, "Für heute sind genug Gespräche geführt. Morgen geht es weiter.", "Für heute sind genug Gespräche geführt. Morgen geht es weiter."),
    voice_unavailable: af(f, "Sprechen ist gerade nicht möglich. Schreiben geht.", "Sprechen ist gerade nicht möglich. Schreiben geht."),
    text_unavailable: "Das Schreiben ist gerade nicht möglich. Bitte versuchen Sie es später noch einmal.",
    connect_failed: af(f, "Die Verbindung zu Viola ließ sich nicht aufbauen. Prüfen Sie Ihre Internetverbindung oder schreiben Sie lieber.", "Die Verbindung zu Viola ließ sich nicht aufbauen. Prüf deine Internetverbindung oder schreib lieber."),
    session_ended: "Das Gespräch ist beendet.",
    too_many_messages: "Für dieses Gespräch sind genug Nachrichten geschrieben. Ein neues geht jederzeit.",
    invalid_token: af(f, "Der Zugang ist abgelaufen. Laden Sie die Seite neu.", "Der Zugang ist abgelaufen. Lade die Seite neu."),
    network: "Keine Verbindung. Bitte prüfen Sie Ihre Internetverbindung.",
    generic: af(f, "Das hat nicht geklappt. Bitte versuchen Sie es gleich noch einmal.", "Das hat nicht geklappt. Bitte versuch es gleich noch einmal."),
  } as Record<string, string>,

  // Verlauf
  historyTitle: "Bisherige Gespräche",
  historyEmpty: "Noch kein Gespräch.",
  historyMode: { voice: "gesprochen", text: "geschrieben" } as Record<string, string>,
  historyStatus: {
    requested: "angefragt",
    active: "läuft",
    completed: "abgeschlossen",
    aborted: "nicht begonnen",
    failed: "unterbrochen",
  } as Record<string, string>,
  summaryStatus: {
    none: "ohne Zusammenfassung",
    draft: "Zusammenfassung zum Lesen",
    confirmed: "Zusammenfassung bestätigt",
    corrected: "Zusammenfassung korrigiert",
    rejected: "Zusammenfassung verworfen",
  } as Record<string, string>,
  transcriptUntil: (date: string) => `Gesprächstext bis ${date} lesbar`,
  transcriptGone: "Gesprächstext gelöscht",
  open: "Ansehen",

  // Bestätigte Zusammenfassung
  profileTitle: af(f, "Ihre Zusammenfassung", "Deine Zusammenfassung"),
  profileConfirmed: (date: string) => `Bestätigt am ${date}`,
  profileNone: af(f, "Noch keine bestätigte Zusammenfassung. Sie entsteht nach dem ersten Gespräch.", "Noch keine bestätigte Zusammenfassung. Sie entsteht nach dem ersten Gespräch."),
});

export const summary = (f: AddressForm) => ({
  title: "Zusammenfassung",
  back: "Zurück zum Gespräch",
  lead: af(
    f,
    "So hat Viola Sie verstanden. Lesen Sie in Ruhe. Was Sie bestätigen, nutzt Fermata für Vorschläge; Ihr Gegenüber sieht diesen Text nie.",
    "So hat Viola dich verstanden. Lies in Ruhe. Was du bestätigst, nutzt Fermata für Vorschläge; dein Gegenüber sieht diesen Text nie.",
  ),
  waiting: "Viola schreibt die Zusammenfassung …",
  waitingText: "Das dauert meist weniger als eine Minute. Die Seite aktualisiert sich von selbst.",
  failed: af(
    f,
    "Für dieses Gespräch gibt es keine Zusammenfassung. Das passiert, wenn es früh endete. Sie können es jederzeit fortsetzen.",
    "Für dieses Gespräch gibt es keine Zusammenfassung. Das passiert, wenn es früh endete. Du kannst es jederzeit fortsetzen.",
  ),
  draftLabel: "Entwurf",
  confirm: "Stimmt so",
  correct: "Korrigieren",
  reject: "Verwerfen",
  correctLabel: af(f, "Ihre Fassung", "Deine Fassung"),
  correctHint: "20 bis 4000 Zeichen. Bitte keine Angaben zu Gesundheit, Religion, Politik, Herkunft oder Sexualität.",
  correctSubmit: "Korrektur speichern",
  correctCancel: "Abbrechen",
  rejectTitle: "Zusammenfassung verwerfen?",
  rejectText: af(
    f,
    "Fermata nutzt diesen Entwurf dann nicht. Sie können jederzeit ein neues Gespräch führen.",
    "Fermata nutzt diesen Entwurf dann nicht. Du kannst jederzeit ein neues Gespräch führen.",
  ),
  rejectConfirm: "Ja, verwerfen",
  confirmed: "Danke. Die Zusammenfassung ist bestätigt.",
  corrected: "Danke. Ihre Korrektur ist gespeichert.",
  rejected: "Der Entwurf ist verworfen.",
  doneConfirmed: (date: string) => `Bestätigt am ${date}.`,
  doneCorrected: (date: string) => `Korrigiert am ${date}.`,
  doneRejected: "Verworfen.",
  art9Title: "Diese Angaben gehören nicht in die Zusammenfassung",
  art9Text: (cats: string) =>
    af(
      f,
      `Ihr Text enthält Angaben zu ${cats}. Solche Angaben speichert Fermata in der Zusammenfassung nicht – zu Ihrem Schutz. Bitte nehmen Sie sie heraus. Religion können Sie, wenn Sie möchten, im geschützten Bereich „Über Sie“ angeben.`,
      `Dein Text enthält Angaben zu ${cats}. Solche Angaben speichert Fermata in der Zusammenfassung nicht – zu deinem Schutz. Bitte nimm sie heraus. Religion kannst du, wenn du möchtest, im geschützten Bereich „Über dich“ angeben.`,
    ),
  art9Categories: {
    gesundheit: "Gesundheit",
    religion: "Religion oder Weltanschauung",
    politik: "politischer Meinung",
    gewerkschaft: "Gewerkschaft",
    herkunft: "Herkunft",
    sexualitaet: "Sexualität",
    geschlecht: "Geschlecht oder gesuchtem Geschlecht",
    genetik: "Genetik oder Biometrie",
    strafrecht: "Straftaten",
  } as Record<string, string>,
  art9Fallback: "geschützten Bereichen",
  errors: {
    invalid_text: "Bitte 20 bis 4000 Zeichen.",
    no_draft: "Für dieses Gespräch gibt es gerade keinen Entwurf.",
    session_not_found: "Dieses Gespräch gibt es nicht.",
    generic: af(f, "Das hat nicht geklappt. Bitte versuchen Sie es gleich noch einmal.", "Das hat nicht geklappt. Bitte versuch es gleich noch einmal."),
  } as Record<string, string>,
  transcriptTitle: "Gesprächstext",
  transcriptLead: (date: string) =>
    af(f, `Nur für Sie lesbar, bis ${date}. Danach wird er gelöscht. Geschützte Angaben sind entfernt.`, `Nur für dich lesbar, bis ${date}. Danach wird er gelöscht. Geschützte Angaben sind entfernt.`),
  transcriptShow: "Gesprächstext zeigen",
  transcriptEmpty: "Kein Gesprächstext gespeichert.",
  speakerViola: "Viola",
  speakerMe: af(f, "Sie", "Du"),
  meta: (kind: string, date: string, mode: string) => `${kind} vom ${date}, ${mode}`,
});
