// Mitgliederbereich: Start, Platzhalter für M3–M7, Konto.
import { af, type AddressForm } from "./form";

export const start = (f: AddressForm) => ({
  title: "Start",
  greeting: (name?: string | null) => (name ? af(f, `Guten Tag, ${name}`, `Hallo ${name}`) : af(f, "Guten Tag", "Hallo")),
  leadOnboarding: af(f, "Schön, dass Sie da sind. Ein paar Schritte noch, dann ist Ihr Konto eingerichtet.", "Schön, dass du da bist. Ein paar Schritte noch, dann ist dein Konto eingerichtet."),
  leadActive: af(f, "Ihr Konto ist eingerichtet.", "Dein Konto ist eingerichtet."),
  nextTitle: "Nächster Schritt",
  next: {
    einwilligungen: { title: "Einwilligungen", text: af(f, "Lesen Sie in Ruhe, wozu Sie zustimmen – jede Einwilligung einzeln.", "Lies in Ruhe, wozu du zustimmst – jede Einwilligung einzeln."), cta: "Weiter mit den Einwilligungen" },
    angaben: { title: af(f, "Ihre Angaben", "Deine Angaben"), text: "Name, Geburtsdatum und Postleitzahl. Ihr Gegenüber sieht davon nichts.", cta: "Angaben ausfüllen" },
    identitaet: { title: af(f, "Über Sie", "Über dich"), text: af(f, "Wer Sie sind und wen Sie kennenlernen möchten.", "Wer du bist und wen du kennenlernen möchtest."), cta: "Weiter" },
    ausweis: { title: "Ausweis prüfen", text: "Einmalig, etwa drei Minuten. Danach löschen wir die Prüfung beim Prüfdienst.", cta: "Zur Ausweisprüfung" },
    fertig: { title: "Gespräch mit Viola", text: af(f, "Viola lernt Sie in einem ruhigen Gespräch kennen. Diese Funktion folgt in Kürze; wir schreiben Ihnen, sobald es losgeht.", "Viola lernt dich in einem ruhigen Gespräch kennen. Diese Funktion folgt in Kürze; wir schreiben dir, sobald es losgeht."), cta: "Mehr zum Gespräch" },
  } as Record<string, { title: string; text: string; cta: string }>,
  progressTitle: af(f, "Ihr Stand", "Dein Stand"),
  membershipTitle: "Mitgliedschaft",
  freePhase: "Gratisphase",
  freePhaseText: "Bis einschließlich zum ersten Abend ist Fermata kostenlos und ohne Karte.",
  eveningsAvailable: (n: number) => (n === 1 ? "1 Abend verfügbar" : `${n} Abende verfügbar`),
  founding: "Gründungsmitglied",
  adminHint: "Sie sind als Admin angemeldet.",
  toAdmin: "Zum Admin-Bereich",
  installTitle: "Fermata auf dem Home-Bildschirm",
  installText: "Als App installiert bekommen Sie Erinnerungen auch auf dem iPhone.",
  installCta: "So geht es",
});

export const konto = (f: AddressForm) => ({
  title: "Konto",
  lead: af(f, "Ihre Angaben, Einwilligungen und Einstellungen – und alles, um Ihre Daten mitzunehmen oder zu löschen.", "Deine Angaben, Einwilligungen und Einstellungen – und alles, um deine Daten mitzunehmen oder zu löschen."),
  factsTitle: af(f, "Ihre Angaben", "Deine Angaben"),
  factsEmpty: "Noch nicht ausgefüllt.",
  labels: { name: "Name", birthDate: "Geburtsdatum", place: "Ort", phone: "Telefon", email: "E-Mail-Adresse", street: "Straße" },
  addressFormTitle: "Anrede und Darstellung",
  identityTitle: af(f, "Über Sie", "Über dich"),
  identityText: af(f, "Geschlecht, wen Sie kennenlernen möchten, Religion (freiwillig). Besonders geschützt und verschlüsselt.", "Geschlecht, wen du kennenlernen möchtest, Religion (freiwillig). Besonders geschützt und verschlüsselt."),
  addressFormSaved: "Gespeichert.",
  consentsTitle: "Einwilligungen",
  consentsLead: af(f, "Hier sehen Sie, wozu Sie zugestimmt haben, und können Einwilligungen widerrufen.", "Hier siehst du, wozu du zugestimmt hast, und kannst Einwilligungen widerrufen."),
  consentsCta: "Einwilligungen ansehen",
  notificationsTitle: "Mitteilungen",
  notificationsText: af(f, "Erinnerungen an Fristen und Abende bekommen Sie immer per E-Mail. Mitteilungen auf dem Gerät folgen mit den Abenden.", "Erinnerungen an Fristen und Abende bekommst du immer per E-Mail. Mitteilungen auf dem Gerät folgen mit den Abenden."),
  dataTitle: af(f, "Ihre Daten", "Deine Daten"),
  exportText: af(f, "Laden Sie alles herunter, was Fermata über Sie gespeichert hat (Art. 15 und 20 DSGVO).", "Lade alles herunter, was Fermata über dich gespeichert hat (Art. 15 und 20 DSGVO)."),
  exportCta: "Daten herunterladen",
  deleteText: af(f, "Konto und Daten endgültig löschen (Art. 17 DSGVO).", "Konto und Daten endgültig löschen (Art. 17 DSGVO)."),
  deleteCta: "Konto löschen",
  sessionTitle: "Anmeldung",
  logout: "Abmelden",
});

export const consents = (f: AddressForm) => ({
  title: "Einwilligungen",
  lead: af(f, "Jede Erteilung und jeder Widerruf wird mit Datum und Fassung des Textes festgehalten.", "Jede Erteilung und jeder Widerruf wird mit Datum und Fassung des Textes festgehalten."),
  granted: (date: string) => `Erteilt am ${date}`,
  notGranted: "Nicht erteilt",
  renewal: "Neue Fassung – bitte erneut lesen",
  read: "Text lesen",
  revoke: "Widerrufen",
  revokeTitle: "Einwilligung widerrufen?",
  revokeText: {
    art9_profile: af(f, "Wir löschen Ihre Angaben zu Geschlecht, Suche und Orientierung sofort. Ohne sie können wir Ihnen keine Abende vorschlagen.", "Wir löschen deine Angaben zu Geschlecht, Suche und Orientierung sofort. Ohne sie können wir dir keine Abende vorschlagen."),
    art9_religion: af(f, "Wir löschen Ihre Angaben zur Religion sofort.", "Wir löschen deine Angaben zur Religion sofort."),
    art9_health: af(f, "Wir löschen Ihre Angaben zur Gesundheit sofort.", "Wir löschen deine Angaben zur Gesundheit sofort."),
    biometrie: af(f, "Ohne diese Einwilligung ist keine neue Ausweisprüfung möglich. Ein schon geprüfter Ausweis bleibt geprüft.", "Ohne diese Einwilligung ist keine neue Ausweisprüfung möglich. Ein schon geprüfter Ausweis bleibt geprüft."),
    gespraech: af(f, "Gespeicherte Gesprächstexte löschen wir sofort.", "Gespeicherte Gesprächstexte löschen wir sofort."),
    push: "Mitteilungen auf allen Geräten werden abgeschaltet.",
    kontakttausch: "Ihre Kontaktdaten werden nicht mehr geteilt.",
  } as Record<string, string>,
  revokeConfirm: "Ja, widerrufen",
  notRevocable: af(f, "Nutzungsbedingungen und Datenschutzhinweise enden mit der Löschung Ihres Kontos.", "Nutzungsbedingungen und Datenschutzhinweise enden mit der Löschung deines Kontos."),
  revoked: "Widerrufen.",
  kinds: {
    agb: "Nutzungsbedingungen",
    datenschutz_kenntnis: "Datenschutzhinweise",
    art9_profile: "Geschlecht und gesuchtes Geschlecht",
    art9_religion: "Religion",
    art9_health: "Gesundheit",
    biometrie: "Ausweisprüfung mit Gesichtsabgleich",
    gespraech: "Gespräch mit Viola",
    push: "Mitteilungen auf dem Gerät",
    kontakttausch: "Kontakt teilen",
  } as Record<string, string>,
  required: "Pflicht",
  optional: "freiwillig",
});

export const dataExport = (f: AddressForm) => ({
  title: af(f, "Ihre Daten herunterladen", "Deine Daten herunterladen"),
  lead: af(
    f,
    "Sie bekommen eine Datei mit allem, was Fermata über Sie gespeichert hat: Konto, Angaben, Einwilligungen, besondere Angaben, Profil, Gespräche, Abende aus Ihrer Sicht, Mitgliedschaft und Ihre Meldungen. Daten über andere Menschen sind nicht enthalten.",
    "Du bekommst eine Datei mit allem, was Fermata über dich gespeichert hat: Konto, Angaben, Einwilligungen, besondere Angaben, Profil, Gespräche, Abende aus deiner Sicht, Mitgliedschaft und deine Meldungen. Daten über andere Menschen sind nicht enthalten.",
  ),
  format: "Format: JSON (maschinenlesbar, Art. 20 DSGVO). Die Datei enthält besonders geschützte Angaben – bewahren Sie sie sicher auf.",
  cta: "Datei herunterladen",
});

export const deletion = (f: AddressForm) => ({
  title: "Konto löschen",
  step1: "Schritt 1 von 2",
  step2: "Schritt 2 von 2",
  lead: af(f, "Wenn Sie Ihr Konto löschen, ist es endgültig weg. Das lässt sich nicht rückgängig machen.", "Wenn du dein Konto löschst, ist es endgültig weg. Das lässt sich nicht rückgängig machen."),
  whatTitle: "Was wir löschen",
  what: [
    "Konto, Anmeldung und Angaben (Name, Geburtsdatum, Ort, Telefon)",
    "Einwilligungen und besonders geschützte Angaben",
    "Ergebnis der Ausweisprüfung",
    "Profil, Wünsche, freie Zeiten, Gesprächstexte",
    "Abende, Rückmeldungen und Mitgliedschaft",
  ],
  keepTitle: "Was bleibt – ohne Bezug zu Ihnen",
  keep: [
    "Rechnungen und Vertragserklärungen, solange das Gesetz es verlangt",
    "Meldungen, die Sie abgegeben haben, ohne Ihren Namen",
    "Ein Protokolleintrag, dass ein Konto gelöscht wurde",
  ],
  exportHint: af(f, "Möchten Sie vorher Ihre Daten herunterladen?", "Möchtest du vorher deine Daten herunterladen?"),
  continue: "Weiter zur Löschung",
  confirmTitle: "Wirklich löschen?",
  confirmLabel: af(f, "Ich möchte mein Konto und meine Daten endgültig löschen.", "Ich möchte mein Konto und meine Daten endgültig löschen."),
  confirmRequired: "Bitte bestätigen Sie die Löschung mit dem Häkchen.",
  submit: "Konto endgültig löschen",
  deleting: "Wird gelöscht …",
  cancel: "Abbrechen und behalten",
  mailNote: af(f, "Sie bekommen danach eine Bestätigung per E-Mail.", "Du bekommst danach eine Bestätigung per E-Mail."),
  adminNotPossible: "Admin-Konten lassen sich hier nicht löschen.",
});
