// Mitteilungen auf dem Gerät (Web-Push, M5) im Konto.
import { af, type AddressForm } from "./form";

export const push = (f: AddressForm) => ({
  title: "Mitteilungen",
  back: "Zurück zum Konto",
  lead: af(
    f,
    "Erinnerungen an Fristen und Abende bekommen Sie immer per E-Mail. Wenn Sie möchten, zusätzlich als Mitteilung auf diesem Gerät.",
    "Erinnerungen an Fristen und Abende bekommst du immer per E-Mail. Wenn du möchtest, zusätzlich als Mitteilung auf diesem Gerät.",
  ),
  facts: [
    "Mitteilungen nennen nie Namen, nur das Nötigste.",
    "Zwischen 22 und 8 Uhr kommen keine Mitteilungen – außer dem Check-in am Abend.",
    "Läuft eine Frist, kommt immer auch eine E-Mail.",
  ],
  cardTitle: "Mitteilungen auf diesem Gerät",
  cardTitleShort: "Mitteilungen",
  kontoText: af(
    f,
    "Erinnerungen bekommen Sie immer per E-Mail. Auf Wunsch auch als Mitteilung auf dem Gerät.",
    "Erinnerungen bekommst du immer per E-Mail. Auf Wunsch auch als Mitteilung auf dem Gerät.",
  ),
  kontoCta: "Mitteilungen einrichten",
  kontoOn: (n: number) => (n === 1 ? "An auf 1 Gerät" : `An auf ${n} Geräten`),
  kontoOff: "Aus",
  enable: "Mitteilungen einschalten",
  enabling: "Wird eingeschaltet …",
  disable: "Auf diesem Gerät ausschalten",
  enabledHere: "Auf diesem Gerät eingeschaltet.",
  notHere: "Auf diesem Gerät aus.",
  checking: "Wird geprüft …",
  test: "So sieht eine Mitteilung aus",
  sample: "Ein Vorschlag für einen Abend. Antwort bis morgen, 18 Uhr.",
  devicesTitle: af(f, "Ihre Geräte", "Deine Geräte"),
  devicesEmpty: "Noch auf keinem Gerät eingeschaltet.",
  platform: { ios: "iPhone oder iPad", android: "Android", desktop: "Computer" } as Record<string, string>,
  platformUnknown: "Gerät",
  thisDevice: "dieses Gerät",
  since: (date: string) => `seit ${date}`,
  lastSuccess: (date: string) => `zuletzt zugestellt am ${date}`,
  remove: "Entfernen",
  removeLabel: (name: string, date: string) => `${name} vom ${date} entfernen`,
  removed: "Entfernt.",
  allOff: "Auf allen Geräten ausschalten",
  allOffText: af(
    f,
    "Widerruft die Einwilligung und entfernt alle Geräte. Sie können Mitteilungen jederzeit wieder einschalten.",
    "Widerruft die Einwilligung und entfernt alle Geräte. Du kannst Mitteilungen jederzeit wieder einschalten.",
  ),
  allOffTitle: "Mitteilungen überall ausschalten?",
  allOffConfirm: "Ja, überall ausschalten",
  allOffDone: "Ausgeschaltet.",
  consentTitle: "Einwilligung für Mitteilungen",
  consentLead: af(
    f,
    "Für Mitteilungen speichert Fermata eine Adresse des Push-Dienstes Ihres Browsers. Dafür brauchen wir einmal Ihre Einwilligung.",
    "Für Mitteilungen speichert Fermata eine Adresse des Push-Dienstes deines Browsers. Dafür brauchen wir einmal deine Einwilligung.",
  ),
  consentAgree: "Ich habe den Text gelesen und willige ein.",
  consentRead: "Ganzen Text lesen",
  iosTitle: "iPhone und iPad",
  iosText: af(
    f,
    "Auf dem iPhone kommen Mitteilungen nur an, wenn Fermata auf dem Home-Bildschirm liegt (ab iOS 16.4). Öffnen Sie Fermata dann über das Symbol und schalten Sie Mitteilungen dort ein.",
    "Auf dem iPhone kommen Mitteilungen nur an, wenn Fermata auf dem Home-Bildschirm liegt (ab iOS 16.4). Öffne Fermata dann über das Symbol und schalte Mitteilungen dort ein.",
  ),
  iosCta: "Anleitung: Zum Home-Bildschirm",
  problems: {
    unsupported: af(f, "Dieser Browser kann keine Mitteilungen empfangen. Die E-Mails kommen trotzdem.", "Dieser Browser kann keine Mitteilungen empfangen. Die E-Mails kommen trotzdem."),
    ios_browser: af(f, "Im Browser-Tab geht das auf dem iPhone nicht. Legen Sie Fermata auf den Home-Bildschirm.", "Im Browser-Tab geht das auf dem iPhone nicht. Leg Fermata auf den Home-Bildschirm."),
    denied: af(
      f,
      "Mitteilungen sind für Fermata im Browser blockiert. Erlauben Sie sie in den Einstellungen der Seite und versuchen Sie es noch einmal.",
      "Mitteilungen sind für Fermata im Browser blockiert. Erlaube sie in den Einstellungen der Seite und versuch es noch einmal.",
    ),
    dismissed: af(f, "Sie haben die Frage des Browsers geschlossen. Versuchen Sie es noch einmal, wenn Sie möchten.", "Du hast die Frage des Browsers geschlossen. Versuch es noch einmal, wenn du möchtest."),
    no_worker: af(f, "Der Hintergrunddienst von Fermata läuft noch nicht. Bitte laden Sie die Seite neu.", "Der Hintergrunddienst von Fermata läuft noch nicht. Bitte lade die Seite neu."),
    push_not_configured: "Mitteilungen sind auf dem Server noch nicht eingerichtet. Die E-Mails kommen trotzdem.",
    subscribe_failed: "Der Browser konnte sich nicht beim Push-Dienst anmelden. Bitte später noch einmal versuchen.",
    consent_missing: "Für Mitteilungen fehlt noch die Einwilligung.",
    invalid_subscription: "Der Browser hat eine ungültige Adresse geliefert. Bitte noch einmal versuchen.",
    generic: af(f, "Das hat nicht geklappt. Bitte versuchen Sie es gleich noch einmal.", "Das hat nicht geklappt. Bitte versuch es gleich noch einmal."),
  } as Record<string, string>,
});
