// Freie Abende (Zeitenabfrage, M5): Raster je Zeitraum.
import { af, type AddressForm } from "./form";

export const zeiten = (f: AddressForm) => ({
  title: "Freie Abende",
  lead: af(
    f,
    "Wann haben Sie in den nächsten zwei Wochen abends Zeit? Wir schlagen nur Abende vor, die in Ihre freien Zeiten passen.",
    "Wann hast du in den nächsten zwei Wochen abends Zeit? Wir schlagen nur Abende vor, die in deine freien Zeiten passen.",
  ),
  periodLabel: (from: string, to: string) => `${from} bis ${to}`,
  deadline: (when: string) => af(f, `Bitte eintragen ${when}.`, `Bitte eintragen ${when}.`),
  closed: af(f, "Die Abfrage für diesen Zeitraum ist abgeschlossen. Ihre Zeiten sind gespeichert.", "Die Abfrage für diesen Zeitraum ist abgeschlossen. Deine Zeiten sind gespeichert."),
  noPeriodTitle: "Gerade keine Abfrage",
  noPeriodText: af(
    f,
    "Alle 14 Tage fragen wir, wann Sie Zeit haben, und schreiben Ihnen dazu. Dann tragen Sie hier Ihre freien Abende ein.",
    "Alle 14 Tage fragen wir, wann du Zeit hast, und schreiben dir dazu. Dann trägst du hier deine freien Abende ein.",
  ),
  otherPeriods: "Weitere Zeiträume",
  howTitle: "So geht es",
  how: [
    af(f, "Tippen Sie auf die halben Stunden, in denen Sie Zeit haben. Zusammenhängende Felder werden ein Zeitfenster.", "Tipp auf die halben Stunden, in denen du Zeit hast. Zusammenhängende Felder werden ein Zeitfenster."),
    "Ein Zeitfenster dauert mindestens 2 Stunden – so lang ist ein Abend.",
    af(f, "Mit „Ganzer Abend“ markieren Sie 17 bis 23 Uhr auf einmal.", "Mit „Ganzer Abend“ markierst du 17 bis 23 Uhr auf einmal."),
    "Mit der Tastatur: Pfeiltasten bewegen, Leertaste oder Enter markiert.",
  ],
  gridLabel: (week: string) => `Freie Zeiten, ${week}`,
  weekLabel: (from: string, to: string) => `Woche vom ${from} bis ${to}`,
  dayColumn: "Tag",
  wholeEvening: "Ganzer Abend",
  clearDay: "Tag leeren",
  wholeEveningLabel: (day: string) => `Ganzer Abend am ${day}`,
  clearDayLabel: (day: string) => `Alle Zeiten am ${day} entfernen`,
  cellLabel: (day: string, from: string, to: string) => `${day}, ${from} bis ${to}`,
  free: "frei",
  past: "vorbei",
  summaryTitle: af(f, "Ihre Zeitfenster", "Deine Zeitfenster"),
  summaryEmpty: "Noch keine Zeiten markiert.",
  summaryWindow: (day: string, from: string, to: string) => `${day}, ${from} bis ${to} Uhr`,
  tooShort: (day: string, from: string, to: string) => `${day}, ${from} bis ${to} Uhr ist kürzer als 2 Stunden.`,
  tooMany: (n: number, max: number) => `${n} Zeitfenster sind zu viele (höchstens ${max}).`,
  save: "Zeiten speichern",
  saving: "Wird gespeichert …",
  saved: af(f, "Gespeichert. Sie können die Zeiten bis zum Ende der Abfrage ändern.", "Gespeichert. Du kannst die Zeiten bis zum Ende der Abfrage ändern."),
  reset: "Änderungen verwerfen",
  unsaved: "Noch nicht gespeichert.",
  outsideGrid: (n: number) =>
    af(
      f,
      `${n === 1 ? "Ein Zeitfenster liegt" : `${n} Zeitfenster liegen`} außerhalb von 17 bis 23 Uhr. Beim Speichern zählt nur, was hier markiert ist.`,
      `${n === 1 ? "Ein Zeitfenster liegt" : `${n} Zeitfenster liegen`} außerhalb von 17 bis 23 Uhr. Beim Speichern zählt nur, was hier markiert ist.`,
    ),
  windowsCount: (n: number) => (n === 1 ? "1 Zeitfenster eingetragen" : `${n} Zeitfenster eingetragen`),
  open: "eintragen",
  closedBadge: "abgeschlossen",
  openBadge: "offen",
  errors: {
    not_authenticated: af(f, "Bitte melden Sie sich an.", "Bitte melde dich an."),
    account_inactive: af(f, "Ihr Konto ist gerade nicht aktiv. Deshalb können Sie keine Zeiten eintragen.", "Dein Konto ist gerade nicht aktiv. Deshalb kannst du keine Zeiten eintragen."),
    period_not_found: "Diesen Zeitraum gibt es nicht.",
    period_closed: "Die Abfrage ist schon abgeschlossen.",
    invalid_input: "Die Zeiten ließen sich nicht lesen. Bitte noch einmal markieren.",
    too_many_windows: "Das sind zu viele Zeitfenster (höchstens 12).",
    window_too_short: "Ein Zeitfenster ist kürzer als 2 Stunden.",
    window_too_long: "Ein Zeitfenster ist länger als 6 Stunden.",
    window_in_past: "Ein Zeitfenster liegt in der Vergangenheit.",
    window_outside_period: "Ein Zeitfenster liegt außerhalb des Zeitraums.",
    windows_overlap: "Zwei Zeitfenster überschneiden sich.",
    generic: af(f, "Das hat nicht geklappt. Bitte versuchen Sie es gleich noch einmal.", "Das hat nicht geklappt. Bitte versuch es gleich noch einmal."),
  } as Record<string, string>,
  back: "Zu den Abenden",
});
